/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.trackmodel;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import trackmodel.TrackModel;
import trackmodel.TrackGraph;
import trackmodel.BetaBlock;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author kwc12
 */
public class TrackModelUI extends javax.swing.JFrame {
    private static ArrayList<Object[][]> Tracks;
    private static TrackModel newTrack;
    private static int lastTemp = 50;
    /**
     * Creates new form TrackModelUI
     */
    public TrackModelUI(){
        
        newTrack = new TrackModel();
        
        initComponents();
        
        Timer timer = new Timer();
        TimerTask tasknew;
        tasknew = new TimerTask() {

            @Override
            public void run() {
                String temp = newTrack.getTemp();
                Auto_Temp_Text_Field.setText(temp);
            }
        };
        timer.schedule(tasknew,10000,10000);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        ExcelTable = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        RedLineTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        GreenLineTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        RedSpecsTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        GreenSpecsTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TrainMap = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AutoTab = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Auto_Temp_Text_Field = new javax.swing.JTextPane();
        Auto_Temp_Label = new javax.swing.JLabel();
        Auto_Heater_Label = new javax.swing.JLabel();
        Auto_Heater_Text_Field = new javax.swing.JTextField();
        NotificationBoardLabel = new javax.swing.JLabel();
        TrainsOnTrackLabel = new javax.swing.JLabel();
        TrainsOntrackField = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        AutoTab_SignalLightsText = new javax.swing.JTextArea();
        FailureModesLabel = new javax.swing.JLabel();
        BrokenRailLabel = new javax.swing.JLabel();
        PowerFailureLabel = new javax.swing.JLabel();
        TrackCircuitFailureLabel = new javax.swing.JLabel();
        ToggleBrokenRail = new javax.swing.JToggleButton();
        TogglePowerFailure = new javax.swing.JToggleButton();
        ToggleTrackCircuitFailure = new javax.swing.JToggleButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        NotificationField = new javax.swing.JTextArea();
        ManualTab = new javax.swing.JPanel();
        Manual_Temp_Label = new javax.swing.JLabel();
        Manual_Temp_Field = new javax.swing.JTextField();
        ChangeTempButton = new javax.swing.JButton();
        ChangeTempField = new javax.swing.JTextField();
        ChangeTempLabel = new javax.swing.JLabel();
        ReconfigureTrackLabel = new javax.swing.JLabel();
        SubmitChangeButton = new javax.swing.JButton();
        ChangeLine = new javax.swing.JTextField();
        ChangeSection = new javax.swing.JTextField();
        ChangeBlockNum = new javax.swing.JTextField();
        ChangeBlockLen = new javax.swing.JTextField();
        ChangeSpeed = new javax.swing.JTextField();
        ChangeInfrastructure = new javax.swing.JTextField();
        ChangeArrow = new javax.swing.JTextField();
        ReconfigureEditor = new javax.swing.JTextField();
        DateOfEdit = new javax.swing.JTextField();
        ChangeSwitch = new javax.swing.JTextField();
        HeaterSwitchLabel = new javax.swing.JLabel();
        HeaterOnRadioButton = new javax.swing.JRadioButton();
        HeaterOffRadioButton = new javax.swing.JRadioButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        ManTab_SignalLightText = new javax.swing.JTextArea();
        DemoTab = new javax.swing.JPanel();
        TrackControllerLabel = new javax.swing.JLabel();
        DemoSetSpeed = new javax.swing.JTextField();
        DemoSetAuthority = new javax.swing.JTextField();
        DemoSetLine = new javax.swing.JTextField();
        DemoSetSection = new javax.swing.JTextField();
        DemoSetOrientation = new javax.swing.JTextField();
        DemoSetLight = new javax.swing.JTextField();
        SubmitInfoToTrainButton = new javax.swing.JButton();
        SubmitInfoToTrackButton = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        DemoTab_SignalLightsText = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("TrackModelUI");

        ExcelTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));

        RedLineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String [] {
                "Line", "Section", "Block #", "Presence Detection", "Signal Lights Normal", "Signal Lights Reverse", "Speed Limit (mph)", "Infrastructure"
            }
        ));
        jScrollPane3.setViewportView(RedLineTable);

        ExcelTable.addTab("Red Line Tracking", jScrollPane3);

        GreenLineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line", "Section", "Block #", "Presence Detection", "Signal Lights Normal", "Signal Lights Reverse", "Speed Limit (mph)", "Infrastructure"
            }
        ));
        jScrollPane5.setViewportView(GreenLineTable);

        ExcelTable.addTab("Green Line Tracking", jScrollPane5);

        RedSpecsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String [] {
                "Line", "Section", "Block Number", "Block Length (ft)", "Block Grade (%)", "Switch Block", "Arrow Direction"
            }
        ));
        jScrollPane4.setViewportView(RedSpecsTable);

        ExcelTable.addTab("Red Line Specs", jScrollPane4);

        GreenSpecsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line", "Section", "Block Number", "Block Length (ft)", "Block Grade (%)", "Switch Block", "Arrow Direction"
            }
        ));
        jScrollPane6.setViewportView(GreenSpecsTable);

        ExcelTable.addTab("Green Line Specs", jScrollPane6);

        TrainMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/trackmodel/media/Track_Layout.png"))); // NOI18N
        TrainMap.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));
        jScrollPane1.setViewportView(TrainMap);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Auto_Temp_Text_Field.setText(newTrack.getTemp());
        jScrollPane7.setViewportView(Auto_Temp_Text_Field);

        Auto_Temp_Label.setText("Temperature º F ");

        Auto_Heater_Label.setText("Heater");

        Auto_Heater_Text_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Auto_Heater_Text_Field.setText("OFF");
        Auto_Heater_Text_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Auto_Heater_Text_FieldActionPerformed(evt);
            }
        });

        NotificationBoardLabel.setText("Messages");

        TrainsOnTrackLabel.setText("Trains On Track");

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        AutoTab_SignalLightsText.setBackground(new java.awt.Color(255, 255, 153));
        AutoTab_SignalLightsText.setColumns(20);
        AutoTab_SignalLightsText.setRows(5);
        AutoTab_SignalLightsText.setText("*Signal Lights: Normal follows tracks in\n alphabetical order. Reverse follows tracks\n in reverse alphabetical order.");
        jScrollPane8.setViewportView(AutoTab_SignalLightsText);

        FailureModesLabel.setText("Failure Modes");

        BrokenRailLabel.setText("Broken Rail:");

        PowerFailureLabel.setText("Power Failure:");

        TrackCircuitFailureLabel.setText("Track Circuit Failure:");

        ToggleBrokenRail.setText("ON/OFF");

        TogglePowerFailure.setText("ON/OFF");

        ToggleTrackCircuitFailure.setText("ON/OFF");

        NotificationField.setColumns(20);
        NotificationField.setRows(5);
        jScrollPane11.setViewportView(NotificationField);

        javax.swing.GroupLayout AutoTabLayout = new javax.swing.GroupLayout(AutoTab);
        AutoTab.setLayout(AutoTabLayout);
        AutoTabLayout.setHorizontalGroup(
            AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutoTabLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TrainsOnTrackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrainsOntrackField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(NotificationBoardLabel)))
                .addGap(126, 126, 126)
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutoTabLayout.createSequentialGroup()
                        .addComponent(Auto_Heater_Label)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutoTabLayout.createSequentialGroup()
                        .addComponent(Auto_Heater_Text_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGap(10, 10, 10)
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Auto_Temp_Label)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TrackCircuitFailureLabel)
                            .addGroup(AutoTabLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BrokenRailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PowerFailureLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ToggleBrokenRail)
                            .addComponent(TogglePowerFailure)
                            .addComponent(ToggleTrackCircuitFailure))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(FailureModesLabel)))
                .addContainerGap(1367, Short.MAX_VALUE))
        );
        AutoTabLayout.setVerticalGroup(
            AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addComponent(FailureModesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AutoTabLayout.createSequentialGroup()
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BrokenRailLabel)
                                    .addComponent(ToggleBrokenRail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TogglePowerFailure)
                                    .addComponent(PowerFailureLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ToggleTrackCircuitFailure)
                                    .addComponent(TrackCircuitFailureLabel)))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TrainsOnTrackLabel)
                            .addComponent(NotificationBoardLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrainsOntrackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AutoTabLayout.createSequentialGroup()
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Auto_Temp_Label)
                                    .addComponent(Auto_Heater_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane7)
                                    .addComponent(Auto_Heater_Text_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Auto", AutoTab);

        Manual_Temp_Label.setText("Temperature º F / º C");

        ChangeTempButton.setText("Change Temp");
        ChangeTempButton.setAlignmentX(0.5F);
        ChangeTempButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ChangeTempField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ChangeTempLabel.setText("Change Temperature (º F)");

        ReconfigureTrackLabel.setText("Reconfigure Track");

        SubmitChangeButton.setText("Submit Change");

        ChangeLine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeLine.setText("Line");

        ChangeSection.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeSection.setText("Section");
        ChangeSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSectionActionPerformed(evt);
            }
        });

        ChangeBlockNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeBlockNum.setText("Block #");

        ChangeBlockLen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeBlockLen.setText("Block Length (m)");

        ChangeSpeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeSpeed.setText("Speed Limit (km/h)");

        ChangeInfrastructure.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeInfrastructure.setText("Infrastructure (optional)");

        ChangeArrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeArrow.setText("Arrow Direction (optional)");
        ChangeArrow.setCursor(new java.awt.Cursor(java.awt.Cursor.NE_RESIZE_CURSOR));

        ReconfigureEditor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ReconfigureEditor.setText("Name (editor)");

        DateOfEdit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DateOfEdit.setText("Date");

        ChangeSwitch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeSwitch.setText("Switch Block (optional)");

        HeaterSwitchLabel.setText("Heater");

        HeaterOnRadioButton.setSelected(true);
        HeaterOnRadioButton.setText("ON");
        HeaterOnRadioButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        HeaterOffRadioButton.setText("OFF");

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ManTab_SignalLightText.setBackground(new java.awt.Color(255, 255, 153));
        ManTab_SignalLightText.setColumns(20);
        ManTab_SignalLightText.setRows(5);
        ManTab_SignalLightText.setText("*Signal Lights: Normal follows tracks in\n alphabetical order. Reverse follows tracks\n in reverse alphabetical order. ");
        jScrollPane9.setViewportView(ManTab_SignalLightText);

        javax.swing.GroupLayout ManualTabLayout = new javax.swing.GroupLayout(ManualTab);
        ManualTab.setLayout(ManualTabLayout);
        ManualTabLayout.setHorizontalGroup(
            ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualTabLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addComponent(ChangeLine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChangeSection, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChangeBlockNum, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChangeBlockLen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReconfigureEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DateOfEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addComponent(ReconfigureTrackLabel)
                                .addGap(37, 37, 37)
                                .addComponent(SubmitChangeButton)))
                        .addGap(155, 155, 155))
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addComponent(ChangeSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeInfrastructure, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeArrow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChangeSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(HeaterOnRadioButton)
                        .addComponent(HeaterSwitchLabel))
                    .addComponent(HeaterOffRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addComponent(ChangeTempLabel)
                        .addGap(18, 18, 18)
                        .addComponent(Manual_Temp_Label))
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addComponent(ChangeTempField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(Manual_Temp_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ChangeTempButton))
                        .addGap(291, 291, 291)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1374, Short.MAX_VALUE))
        );
        ManualTabLayout.setVerticalGroup(
            ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addComponent(HeaterSwitchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HeaterOnRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HeaterOffRadioButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManualTabLayout.createSequentialGroup()
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReconfigureTrackLabel)
                            .addComponent(SubmitChangeButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChangeLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeBlockNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeBlockLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReconfigureEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateOfEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChangeSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeInfrastructure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeArrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Manual_Temp_Label)
                            .addComponent(ChangeTempLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Manual_Temp_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChangeTempField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChangeTempButton))
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manual", ManualTab);

        TrackControllerLabel.setText("Track Controller");

        DemoSetSpeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetSpeed.setText("Speed (km/h)");

        DemoSetAuthority.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetAuthority.setText("Authority (m)");

        DemoSetLine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetLine.setText("Line (Red/Green)");
        DemoSetLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoSetLineActionPerformed(evt);
            }
        });

        DemoSetSection.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetSection.setText("Section (Letter)");

        DemoSetOrientation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetOrientation.setText("Orientation (Normal/Reverse)");

        DemoSetLight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetLight.setText("Light Color (Red/Green)");
        DemoSetLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoSetLightActionPerformed(evt);
            }
        });

        SubmitInfoToTrainButton.setText("Submit to Train");

        SubmitInfoToTrackButton.setText("Submit to Track");

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        DemoTab_SignalLightsText.setBackground(new java.awt.Color(255, 255, 153));
        DemoTab_SignalLightsText.setColumns(20);
        DemoTab_SignalLightsText.setRows(5);
        DemoTab_SignalLightsText.setText("*Signal Lights: Normal follows track in\n alphabetical order. Reverse follows \n track in reverse alphabetical order.");
        jScrollPane10.setViewportView(DemoTab_SignalLightsText);

        javax.swing.GroupLayout DemoTabLayout = new javax.swing.GroupLayout(DemoTab);
        DemoTab.setLayout(DemoTabLayout);
        DemoTabLayout.setHorizontalGroup(
            DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemoTabLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitInfoToTrainButton)
                    .addComponent(SubmitInfoToTrackButton))
                .addGap(18, 18, 18)
                .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DemoTabLayout.createSequentialGroup()
                        .addComponent(DemoSetSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrackControllerLabel)
                            .addComponent(DemoSetAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DemoTabLayout.createSequentialGroup()
                        .addComponent(DemoSetLine, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DemoSetSection, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DemoSetOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DemoSetLight, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(423, 423, 423)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1401, Short.MAX_VALUE))
        );
        DemoTabLayout.setVerticalGroup(
            DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TrackControllerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DemoTabLayout.createSequentialGroup()
                        .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DemoSetSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitInfoToTrainButton)
                            .addComponent(DemoSetAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DemoSetLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DemoSetSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DemoSetOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DemoSetLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitInfoToTrackButton)))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Demo", DemoTab);

        jScrollPane2.setViewportView(jTabbedPane1);

        jMenu1.setBackground(new java.awt.Color(153, 102, 0));
        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Open);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExcelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExcelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        ExcelTable.getAccessibleContext().setAccessibleName("Block List");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Auto_Heater_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Auto_Heater_Text_FieldActionPerformed
        // TODO add your handling code here:
        int outside = Integer.parseInt(Auto_Temp_Text_Field.getText());
        if(lastTemp < 32 && outside < 32){
            Auto_Heater_Text_Field.setText("ON");
        }else if(lastTemp <=32 && outside > 37){
            Auto_Heater_Text_Field.setText("OFF");
        }else if(lastTemp > 32 && outside < 32){
            Auto_Heater_Text_Field.setText("ON");
        }
        lastTemp = outside;
    }//GEN-LAST:event_Auto_Heater_Text_FieldActionPerformed

    private void ChangeSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeSectionActionPerformed

    private void DemoSetLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoSetLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DemoSetLineActionPerformed

    private void DemoSetLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoSetLightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DemoSetLightActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        //NotificationField.setText(filename);
        try{
            
            try{
                newTrack.setDataFile(filename);
                newTrack.ExcelToJavaGraph();
            }catch(Exception e){
                System.out.println("Excel to Graph did not run properly.");
            }
            Object[][] Line;
            Object[][] Specs;
            BetaBlock extractLine;
            int numLine = 2;
            int k;
            for(k=0;k<numLine;k++){
                int theRealCount;
                if(k==0){
                    theRealCount = newTrack.getRedCount();
                }else{
                    theRealCount = newTrack.getGreenCount();
                }
                Line = new Object[theRealCount][8];
                Specs = new Object[theRealCount][7];
                TrackGraph theRealGraph;
                if(k==0){
                    theRealGraph = newTrack.getRedLine();
                }else{
                    theRealGraph = newTrack.getGreenLine();
                }
                System.out.println("About to add data to array.");
                String Name;
                int i;
                for(i = 0; i< theRealCount;i++){
                    if(k==0){
                        Name = "Red"+(i+1);
                    }else{
                        Name = "Green"+(i+1);
                    }
                    System.out.println(Name);
                    extractLine = theRealGraph.getBlock(Name);
                    System.out.println(extractLine.getLabel());
                    Line[i][0] = extractLine.getLine();
                    Line[i][1] = extractLine.getSection();
                    Line[i][2] = (Integer)extractLine.getBlockNum();
                    Line[i][3] = null;
                    Line[i][4] = null;
                    Line[i][5] = null;
                    Line[i][6] = (Integer)extractLine.getSpeedLimit();
                    Line[i][7] = extractLine.getInfraStructure();
                    Specs[i][0] = extractLine.getLine();
                    Specs[i][1] = extractLine.getSection();
                    Specs[i][2] = (Integer)extractLine.getBlockNum();
                    Specs[i][3] = (Double)extractLine.getBlockLength();
                    Specs[i][4] = (Double)extractLine.getBlockGrade();
                    Specs[i][5] = extractLine.getSwitchBlock();
                    Specs[i][6] = extractLine.getArrowDirection();
                }
                if(k==0){
                    RedLineTable.setModel(new javax.swing.table.DefaultTableModel(
                    Line,
                    new String [] {
                        "Line", "Section", "Block #", "Presence Detection", "Signal Lights Normal", "Signal Lights Reverse", "Speed Limit (mph)", "Infrastructure"
                        }
                    ));
                    RedSpecsTable.setModel(new javax.swing.table.DefaultTableModel(
                    Specs,
                    new String [] {
                        "Line", "Section", "Block Number", "Block Length (ft)", "Block Grade (%)", "Switch Block", "Arrow Direction"
                        }
                    ));
                }else{
                    GreenLineTable.setModel(new javax.swing.table.DefaultTableModel(
                    Line,
                    new String [] {
                        "Line", "Section", "Block #", "Presence Detection", "Signal Lights Normal", "Signal Lights Reverse", "Speed Limit (mph)", "Infrastructure"
                        }
                    ));
                    GreenSpecsTable.setModel(new javax.swing.table.DefaultTableModel(
                    Specs,
                    new String [] {
                        "Line", "Section", "Block Number", "Block Length (ft)", "Block Grade (%)", "Switch Block", "Arrow Direction"
                        }
                    ));
                }
            }
            
            
        }catch(Exception e){
            System.out.println("File isn't formatted correctly.");
        }
        
    }//GEN-LAST:event_OpenActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        System.out.println("TrackModelUI is running.");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackModelUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AutoTab;
    private javax.swing.JTextArea AutoTab_SignalLightsText;
    private javax.swing.JLabel Auto_Heater_Label;
    private javax.swing.JTextField Auto_Heater_Text_Field;
    private javax.swing.JLabel Auto_Temp_Label;
    private javax.swing.JTextPane Auto_Temp_Text_Field;
    private javax.swing.JLabel BrokenRailLabel;
    private javax.swing.JTextField ChangeArrow;
    private javax.swing.JTextField ChangeBlockLen;
    private javax.swing.JTextField ChangeBlockNum;
    private javax.swing.JTextField ChangeInfrastructure;
    private javax.swing.JTextField ChangeLine;
    private javax.swing.JTextField ChangeSection;
    private javax.swing.JTextField ChangeSpeed;
    private javax.swing.JTextField ChangeSwitch;
    private javax.swing.JButton ChangeTempButton;
    private javax.swing.JTextField ChangeTempField;
    private javax.swing.JLabel ChangeTempLabel;
    private javax.swing.JTextField DateOfEdit;
    private javax.swing.JTextField DemoSetAuthority;
    private javax.swing.JTextField DemoSetLight;
    private javax.swing.JTextField DemoSetLine;
    private javax.swing.JTextField DemoSetOrientation;
    private javax.swing.JTextField DemoSetSection;
    private javax.swing.JTextField DemoSetSpeed;
    private javax.swing.JPanel DemoTab;
    private javax.swing.JTextArea DemoTab_SignalLightsText;
    private javax.swing.JTabbedPane ExcelTable;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JLabel FailureModesLabel;
    private javax.swing.JTable GreenLineTable;
    private javax.swing.JTable GreenSpecsTable;
    private javax.swing.JRadioButton HeaterOffRadioButton;
    private javax.swing.JRadioButton HeaterOnRadioButton;
    private javax.swing.JLabel HeaterSwitchLabel;
    private javax.swing.JTextArea ManTab_SignalLightText;
    private javax.swing.JPanel ManualTab;
    private javax.swing.JTextField Manual_Temp_Field;
    private javax.swing.JLabel Manual_Temp_Label;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel NotificationBoardLabel;
    private javax.swing.JTextArea NotificationField;
    private javax.swing.JMenuItem Open;
    private javax.swing.JLabel PowerFailureLabel;
    private javax.swing.JTextField ReconfigureEditor;
    private javax.swing.JLabel ReconfigureTrackLabel;
    private javax.swing.JTable RedLineTable;
    private javax.swing.JTable RedSpecsTable;
    private javax.swing.JButton SubmitChangeButton;
    private javax.swing.JButton SubmitInfoToTrackButton;
    private javax.swing.JButton SubmitInfoToTrainButton;
    private javax.swing.JToggleButton ToggleBrokenRail;
    private javax.swing.JToggleButton TogglePowerFailure;
    private javax.swing.JToggleButton ToggleTrackCircuitFailure;
    private javax.swing.JLabel TrackCircuitFailureLabel;
    private javax.swing.JLabel TrackControllerLabel;
    private javax.swing.JLabel TrainMap;
    private javax.swing.JLabel TrainsOnTrackLabel;
    private javax.swing.JTextField TrainsOntrackField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
} 
