/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wonderfresh.trackcontroller;

/**
 *
 * @author obkeel
 */
public class TrackControllerUI extends javax.swing.JFrame {

    /**
     * Creates new form TrackControllerPickerUI
     */
    public TrackControllerUI(PLCRunner1 plc) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TrackControllerPane = new javax.swing.JPanel();
        TrainIDText = new javax.swing.JTextField();
        RouteIDText = new javax.swing.JTextField();
        SpeedLabel = new javax.swing.JLabel();
        SpeedText = new javax.swing.JTextField();
        PowerText = new javax.swing.JTextField();
        SpeedLabel1 = new javax.swing.JLabel();
        SpeedLabel2 = new javax.swing.JLabel();
        SpeedLabel3 = new javax.swing.JLabel();
        SpeedLabel5 = new javax.swing.JLabel();
        SpeedLabel6 = new javax.swing.JLabel();
        SpeedText1 = new javax.swing.JTextField();
        PowerLabel1 = new javax.swing.JLabel();
        PowerLabel2 = new javax.swing.JLabel();
        PowerLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        SpeedText3 = new javax.swing.JTextField();
        SpeedText4 = new javax.swing.JTextField();
        TrackControllerPane2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TrackControllerPane3 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        TrackControllerPane4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TrackControllerPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Block Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 16)));

        TrainIDText.setText("45");

        RouteIDText.setText("Green Line");

        SpeedLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        SpeedLabel.setText("Section:");

        SpeedText.setText("No crossing in this block.");

        PowerText.setText("Yes");

        SpeedLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        SpeedLabel1.setText("Line:");

        SpeedLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        SpeedLabel2.setText("Block:");

        SpeedLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        SpeedLabel3.setText("Set Speed:");

        SpeedLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        SpeedLabel5.setText("Crossing:");

        SpeedLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        SpeedLabel6.setText("Signal:");

        SpeedText1.setText("Green Light");

        PowerLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        PowerLabel1.setText("Switch:");

        PowerLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        PowerLabel2.setText("Open:");

        PowerLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        PowerLabel3.setText("Train Present:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Section A", "Section B", "Section C", "Section D" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Block 1", "Block 2", "Block 3", "Block 4" }));

        SpeedText3.setText("Switch connected to Block 2");

        SpeedText4.setText("No");

        javax.swing.GroupLayout TrackControllerPaneLayout = new javax.swing.GroupLayout(TrackControllerPane);
        TrackControllerPane.setLayout(TrackControllerPaneLayout);
        TrackControllerPaneLayout.setHorizontalGroup(
            TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrackControllerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PowerLabel3)
                    .addComponent(PowerLabel1)
                    .addComponent(SpeedLabel6)
                    .addComponent(SpeedLabel5)
                    .addComponent(SpeedLabel3)
                    .addComponent(SpeedLabel)
                    .addComponent(SpeedLabel1)
                    .addComponent(SpeedLabel2)
                    .addComponent(PowerLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RouteIDText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrainIDText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SpeedText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SpeedText1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SpeedText3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PowerText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SpeedText4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        TrackControllerPaneLayout.setVerticalGroup(
            TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrackControllerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedLabel1)
                    .addComponent(RouteIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedLabel)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedLabel2)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedLabel3)
                    .addComponent(TrainIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedLabel5)
                    .addComponent(SpeedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeedLabel6)
                    .addComponent(SpeedText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerLabel1)
                    .addComponent(SpeedText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerLabel2)
                    .addComponent(PowerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrackControllerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerLabel3)
                    .addComponent(SpeedText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TrackControllerPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upload PLC Program", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 16)));

        jTextField1.setText("C:/Users/obkeel/Documents/PLC.txt");

        jButton1.setText("Pick File");

        jButton2.setText("Submit File");

        javax.swing.GroupLayout TrackControllerPane2Layout = new javax.swing.GroupLayout(TrackControllerPane2);
        TrackControllerPane2.setLayout(TrackControllerPane2Layout);
        TrackControllerPane2Layout.setHorizontalGroup(
            TrackControllerPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrackControllerPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TrackControllerPane2Layout.setVerticalGroup(
            TrackControllerPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrackControllerPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrackControllerPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TrackControllerPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Running Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 16)));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active Mode", "Test Mode" }));

        jButton3.setText("Set Mode");

        javax.swing.GroupLayout TrackControllerPane3Layout = new javax.swing.GroupLayout(TrackControllerPane3);
        TrackControllerPane3.setLayout(TrackControllerPane3Layout);
        TrackControllerPane3Layout.setHorizontalGroup(
            TrackControllerPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrackControllerPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        TrackControllerPane3Layout.setVerticalGroup(
            TrackControllerPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrackControllerPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrackControllerPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TrackControllerPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notifications", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 16)));

        javax.swing.GroupLayout TrackControllerPane4Layout = new javax.swing.GroupLayout(TrackControllerPane4);
        TrackControllerPane4.setLayout(TrackControllerPane4Layout);
        TrackControllerPane4Layout.setHorizontalGroup(
            TrackControllerPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TrackControllerPane4Layout.setVerticalGroup(
            TrackControllerPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "- Track Closures", "- Communication with Communications Controller", "- Change in Track Model Values", "- Light and switch activations" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TrackControllerPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrackControllerPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrackControllerPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrackControllerPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrackControllerPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TrackControllerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TrackControllerPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TrackControllerPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackControllerUI(new PLCRunner1()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PowerLabel1;
    private javax.swing.JLabel PowerLabel2;
    private javax.swing.JLabel PowerLabel3;
    private javax.swing.JTextField PowerText;
    private javax.swing.JTextField RouteIDText;
    private javax.swing.JLabel SpeedLabel;
    private javax.swing.JLabel SpeedLabel1;
    private javax.swing.JLabel SpeedLabel2;
    private javax.swing.JLabel SpeedLabel3;
    private javax.swing.JLabel SpeedLabel5;
    private javax.swing.JLabel SpeedLabel6;
    private javax.swing.JTextField SpeedText;
    private javax.swing.JTextField SpeedText1;
    private javax.swing.JTextField SpeedText3;
    private javax.swing.JTextField SpeedText4;
    private javax.swing.JPanel TrackControllerPane;
    private javax.swing.JPanel TrackControllerPane2;
    private javax.swing.JPanel TrackControllerPane3;
    private javax.swing.JPanel TrackControllerPane4;
    private javax.swing.JTextField TrainIDText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
