/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wonderfresh.trainmodel;

import java.awt.Color;

/**
 *
 * @author Cami
 */
public class TrainModelUI extends javax.swing.JFrame {
    static TrainModel trainModel;
    ApproachingStation approachingStation;
    /**
     * Creates new form frame
     */
    public TrainModelUI(TrainModel train) {
        trainModel = train;
        approachingStation = new ApproachingStation(this);
        initComponents();
        
        yellowPioneer.setVisible(false);
        yellowEdgebrook.setVisible(false);
        yellowDormont.setVisible(false);
        yellowOverbrook.setVisible(false);
        yellowMtLebanon.setVisible(false);
        yellowCastleShannon.setVisible(false);
        yellowSouthHills.setVisible(false);
        yellowStation.setVisible(false);
        yellowWhited.setVisible(false);
        yellowCentral.setVisible(false);
        yellowInglewood.setVisible(false);
        yellowGlenbury.setVisible(false);
        yellowPoplar.setVisible(false);
        yellowFirst.setVisible(false);
        yellowSwissvale.setVisible(false);
        yellowShadyside.setVisible(false);
        yellowPennStation.setVisible(false);
        yellowSteelPlaza.setVisible(false);
        yellowHerron.setVisible(false);
        yellowStationSquare.setVisible(false);
        yellowSouthBank.setVisible(false);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainIDPanel = new javax.swing.JPanel();
        trainIDLabel = new javax.swing.JLabel();
        trainIDbox = new javax.swing.JTextArea();
        speedPanel = new javax.swing.JPanel();
        spsLabel = new javax.swing.JLabel();
        speedLimitLabel = new javax.swing.JLabel();
        powerCmdLabel = new javax.swing.JLabel();
        actualSpeedLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        speedBox = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        spsBox = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        speedLimitBox = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        powerCmdBox = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        attributePanel = new javax.swing.JPanel();
        acLabel = new javax.swing.JLabel();
        acOffLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acOnLabel = new javax.swing.JLabel();
        heatLabel = new javax.swing.JLabel();
        heatOnLabel = new javax.swing.JLabel();
        lightsLabel = new javax.swing.JLabel();
        doorsLabel = new javax.swing.JLabel();
        heatOffLabel = new javax.swing.JLabel();
        serviceBrakesOffLabel = new javax.swing.JLabel();
        serviceBrakeLabel = new javax.swing.JLabel();
        serviceBrakesOnLabel = new javax.swing.JLabel();
        eBrakeLabel = new javax.swing.JLabel();
        eBrakeOnLabel = new javax.swing.JLabel();
        eBrakeOffLabel = new javax.swing.JLabel();
        powerFailureLabel = new javax.swing.JLabel();
        brakeFailureLabel = new javax.swing.JLabel();
        antennaFailureLabel = new javax.swing.JLabel();
        lightsOnLabel = new javax.swing.JLabel();
        lightsOffLabel = new javax.swing.JLabel();
        rightDoorsOpenLabel = new javax.swing.JLabel();
        doorsClosedLabel = new javax.swing.JLabel();
        leftDoorsOpenLabel = new javax.swing.JLabel();
        undergroundLabel = new javax.swing.JLabel();
        notificationPanel = new javax.swing.JPanel();
        notificationsScrollPane = new javax.swing.JScrollPane();
        notificationsBox = new javax.swing.JTextArea();
        emergencyPanel = new javax.swing.JPanel();
        eBrakeButton = new javax.swing.JButton();
        routePanel = new javax.swing.JLayeredPane();
        numPassengersLabel = new javax.swing.JLabel();
        numCrewLabel = new javax.swing.JLabel();
        numPassengersDisemLabel = new javax.swing.JLabel();
        maxPassengerCapacityLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tempBox = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        numCrewBox = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        numPassBox = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        numDisembarkingBox = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        maxPassCapacityBox = new javax.swing.JTextArea();
        redLinePanel = new javax.swing.JPanel();
        redLineRouteImage = new javax.swing.JLabel();
        redLineLabel = new javax.swing.JLabel();
        yellowSouthBank = new javax.swing.JLabel();
        greenLinePanel = new javax.swing.JPanel();
        greenLineRouteImage = new javax.swing.JLabel();
        greenLineLabel = new javax.swing.JLabel();
        redLineLightPanel = new javax.swing.JPanel();
        yellowSwissvale = new javax.swing.JLabel();
        yellowFirst = new javax.swing.JLabel();
        yellowSouthHills = new javax.swing.JLabel();
        yellowHerron = new javax.swing.JLabel();
        yellowPennStation = new javax.swing.JLabel();
        yellowSteelPlaza = new javax.swing.JLabel();
        yellowStationSquare = new javax.swing.JLabel();
        yellowShadyside = new javax.swing.JLabel();
        greenLineLightPanel = new javax.swing.JPanel();
        yellowEdgebrook = new javax.swing.JLabel();
        yellowDormont = new javax.swing.JLabel();
        yellowMtLebanon = new javax.swing.JLabel();
        yellowPioneer = new javax.swing.JLabel();
        yellowWhited = new javax.swing.JLabel();
        yellowCastleShannon = new javax.swing.JLabel();
        yellowPoplar = new javax.swing.JLabel();
        yellowGlenbury = new javax.swing.JLabel();
        yellowInglewood = new javax.swing.JLabel();
        yellowOverbrook = new javax.swing.JLabel();
        yellowStation = new javax.swing.JLabel();
        yellowCentral = new javax.swing.JLabel();
        failurePanel = new javax.swing.JPanel();
        failACButton = new javax.swing.JButton();
        failHeatButton = new javax.swing.JButton();
        failLightsButton = new javax.swing.JButton();
        failLDoorsButton = new javax.swing.JButton();
        failRDoorsButton = new javax.swing.JButton();
        failBrakesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        trainIDPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, null), "Train ID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        trainIDLabel.setText("Train ID");

        trainIDbox.setEditable(false);
        trainIDbox.setColumns(20);
        trainIDbox.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        trainIDbox.setRows(5);

        javax.swing.GroupLayout trainIDPanelLayout = new javax.swing.GroupLayout(trainIDPanel);
        trainIDPanel.setLayout(trainIDPanelLayout);
        trainIDPanelLayout.setHorizontalGroup(
            trainIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainIDPanelLayout.createSequentialGroup()
                .addGroup(trainIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trainIDPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(trainIDLabel))
                    .addGroup(trainIDPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(trainIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        trainIDPanelLayout.setVerticalGroup(
            trainIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainIDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainIDLabel)
                .addGap(18, 18, 18)
                .addComponent(trainIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        speedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Speed", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        spsLabel.setText("Set Point: ");

        speedLimitLabel.setText("Limit: ");

        powerCmdLabel.setText("Power Command: ");

        actualSpeedLabel.setText("Actual: ");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        speedBox.setEditable(false);
        speedBox.setColumns(20);
        speedBox.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        speedBox.setRows(5);
        jScrollPane1.setViewportView(speedBox);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        spsBox.setEditable(false);
        spsBox.setColumns(20);
        spsBox.setRows(5);
        jScrollPane2.setViewportView(spsBox);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        speedLimitBox.setEditable(false);
        speedLimitBox.setColumns(20);
        speedLimitBox.setRows(5);
        jScrollPane3.setViewportView(speedLimitBox);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        powerCmdBox.setEditable(false);
        powerCmdBox.setColumns(20);
        powerCmdBox.setRows(5);
        jScrollPane4.setViewportView(powerCmdBox);

        jLabel1.setText("kW");

        jLabel2.setText("mi/h");

        jLabel4.setText("mi/h");

        jLabel5.setText("mi/h");

        javax.swing.GroupLayout speedPanelLayout = new javax.swing.GroupLayout(speedPanel);
        speedPanel.setLayout(speedPanelLayout);
        speedPanelLayout.setHorizontalGroup(
            speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(speedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualSpeedLabel)
                    .addGroup(speedPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(6, 6, 6)
                .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(speedPanelLayout.createSequentialGroup()
                        .addComponent(powerCmdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(speedPanelLayout.createSequentialGroup()
                        .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spsLabel)
                            .addComponent(speedLimitLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        speedPanelLayout.setVerticalGroup(
            speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(speedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(actualSpeedLabel)
                        .addComponent(spsLabel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(speedPanelLayout.createSequentialGroup()
                        .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speedLimitLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(powerCmdLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, speedPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        attributePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, null), "Attributes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        acLabel.setText("A/C");

        acOffLabel.setText("Off");

        acOnLabel.setForeground(new java.awt.Color(120, 120, 120));
        acOnLabel.setText("On");

        heatLabel.setText("Heat");

        heatOnLabel.setForeground(new java.awt.Color(120, 120, 120));
        heatOnLabel.setText("On");

        lightsLabel.setText("Lights");

        doorsLabel.setText("Doors");

        heatOffLabel.setText("Off");

        serviceBrakesOffLabel.setText("Off");

        serviceBrakeLabel.setText("Service Brakes");

        serviceBrakesOnLabel.setForeground(new java.awt.Color(120, 120, 120));
        serviceBrakesOnLabel.setText("On");

        eBrakeLabel.setText("Emergency Brakes");

        eBrakeOnLabel.setForeground(new java.awt.Color(120, 120, 120));
        eBrakeOnLabel.setText("On");

        eBrakeOffLabel.setText("Off");

        powerFailureLabel.setForeground(new java.awt.Color(120, 120, 120));
        powerFailureLabel.setText("POWER FAILURE");

        brakeFailureLabel.setForeground(new java.awt.Color(120, 120, 120));
        brakeFailureLabel.setText("BRAKE FAILURE");

        antennaFailureLabel.setForeground(new java.awt.Color(120, 120, 120));
        antennaFailureLabel.setText("ANTENNA FAILURE");

        lightsOnLabel.setForeground(new java.awt.Color(120, 120, 120));
        lightsOnLabel.setText("On");

        lightsOffLabel.setText("Off");

        rightDoorsOpenLabel.setForeground(new java.awt.Color(120, 120, 120));
        rightDoorsOpenLabel.setText("Right");

        doorsClosedLabel.setText("Closed");

        leftDoorsOpenLabel.setForeground(new java.awt.Color(120, 120, 120));
        leftDoorsOpenLabel.setText("Left");

        undergroundLabel.setForeground(new java.awt.Color(120, 120, 120));
        undergroundLabel.setText("UNDERGROUND");

        javax.swing.GroupLayout attributePanelLayout = new javax.swing.GroupLayout(attributePanel);
        attributePanel.setLayout(attributePanelLayout);
        attributePanelLayout.setHorizontalGroup(
            attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attributePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attributePanelLayout.createSequentialGroup()
                        .addComponent(leftDoorsOpenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rightDoorsOpenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doorsClosedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(attributePanelLayout.createSequentialGroup()
                        .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(attributePanelLayout.createSequentialGroup()
                                .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heatOnLabel)
                                    .addComponent(heatLabel)
                                    .addComponent(acLabel)
                                    .addComponent(lightsLabel)
                                    .addComponent(acOnLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heatOffLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(acOffLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(attributePanelLayout.createSequentialGroup()
                                .addComponent(lightsOnLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lightsOffLabel))
                            .addGroup(attributePanelLayout.createSequentialGroup()
                                .addComponent(serviceBrakesOnLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(serviceBrakesOffLabel))
                            .addGroup(attributePanelLayout.createSequentialGroup()
                                .addComponent(eBrakeOnLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eBrakeOffLabel))
                            .addGroup(attributePanelLayout.createSequentialGroup()
                                .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eBrakeLabel)
                                    .addComponent(powerFailureLabel)
                                    .addComponent(brakeFailureLabel)
                                    .addComponent(doorsLabel)
                                    .addComponent(serviceBrakeLabel)
                                    .addComponent(antennaFailureLabel)
                                    .addComponent(undergroundLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        attributePanelLayout.setVerticalGroup(
            attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attributePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acLabel)
                .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attributePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acOnLabel)
                            .addComponent(acOffLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heatOnLabel)
                            .addComponent(heatOffLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lightsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lightsOnLabel)
                            .addComponent(lightsOffLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doorsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leftDoorsOpenLabel)
                            .addComponent(rightDoorsOpenLabel)
                            .addComponent(doorsClosedLabel)))
                    .addGroup(attributePanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceBrakeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceBrakesOnLabel)
                    .addComponent(serviceBrakesOffLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eBrakeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eBrakeOnLabel)
                    .addComponent(eBrakeOffLabel))
                .addGap(26, 26, 26)
                .addComponent(undergroundLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powerFailureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brakeFailureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(antennaFailureLabel))
        );

        notificationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null), "Notifications", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        notificationsBox.setEditable(false);
        notificationsBox.setColumns(20);
        notificationsBox.setRows(5);
        notificationsScrollPane.setViewportView(notificationsBox);

        javax.swing.GroupLayout notificationPanelLayout = new javax.swing.GroupLayout(notificationPanel);
        notificationPanel.setLayout(notificationPanelLayout);
        notificationPanelLayout.setHorizontalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notificationsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        notificationPanelLayout.setVerticalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notificationsScrollPane)
        );

        emergencyPanel.setBackground(new java.awt.Color(255, 0, 0));

        eBrakeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eBrakeButton.setText("Emergency Brake");
        eBrakeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 138, 140), null, null));
        eBrakeButton.setContentAreaFilled(false);
        eBrakeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eBrakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setEBrakeLabel(evt);
            }
        });

        javax.swing.GroupLayout emergencyPanelLayout = new javax.swing.GroupLayout(emergencyPanel);
        emergencyPanel.setLayout(emergencyPanelLayout);
        emergencyPanelLayout.setHorizontalGroup(
            emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eBrakeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        emergencyPanelLayout.setVerticalGroup(
            emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eBrakeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        routePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        routePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        numPassengersLabel.setText("Passengers on Board: ");

        numCrewLabel.setText("Crew on Board: ");

        numPassengersDisemLabel.setText("Passengers Disembarking: ");

        maxPassengerCapacityLabel.setText("Max Passenger Capacity: ");

        tempLabel.setText("Temperature: ");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tempBox.setEditable(false);
        tempBox.setColumns(20);
        tempBox.setRows(5);
        jScrollPane5.setViewportView(tempBox);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        numCrewBox.setEditable(false);
        numCrewBox.setColumns(20);
        numCrewBox.setRows(5);
        jScrollPane6.setViewportView(numCrewBox);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        numPassBox.setEditable(false);
        numPassBox.setColumns(20);
        numPassBox.setRows(5);
        jScrollPane7.setViewportView(numPassBox);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        numDisembarkingBox.setEditable(false);
        numDisembarkingBox.setColumns(20);
        numDisembarkingBox.setRows(5);
        jScrollPane8.setViewportView(numDisembarkingBox);

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        maxPassCapacityBox.setEditable(false);
        maxPassCapacityBox.setColumns(20);
        maxPassCapacityBox.setRows(5);
        jScrollPane9.setViewportView(maxPassCapacityBox);

        redLinePanel.setMaximumSize(new java.awt.Dimension(665, 137));
        redLinePanel.setMinimumSize(new java.awt.Dimension(665, 137));
        redLinePanel.setOpaque(false);

        redLineRouteImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wonderfresh/trainmodel/routeImage/ECE1186redLine.png"))); // NOI18N
        redLineRouteImage.setMaximumSize(new java.awt.Dimension(665, 137));
        redLineRouteImage.setMinimumSize(new java.awt.Dimension(665, 137));

        redLineLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        redLineLabel.setForeground(new java.awt.Color(255, 0, 0));
        redLineLabel.setText("Red Line");

        yellowSouthBank.setBackground(new java.awt.Color(255, 255, 0));
        yellowSouthBank.setForeground(new java.awt.Color(255, 255, 0));
        yellowSouthBank.setOpaque(true);

        javax.swing.GroupLayout redLinePanelLayout = new javax.swing.GroupLayout(redLinePanel);
        redLinePanel.setLayout(redLinePanelLayout);
        redLinePanelLayout.setHorizontalGroup(
            redLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redLinePanelLayout.createSequentialGroup()
                .addComponent(redLineRouteImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(redLinePanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(yellowSouthBank, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(redLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLinePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(redLineLabel)
                    .addContainerGap(587, Short.MAX_VALUE)))
        );
        redLinePanelLayout.setVerticalGroup(
            redLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redLinePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yellowSouthBank, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redLineRouteImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(redLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLinePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(redLineLabel)
                    .addContainerGap(134, Short.MAX_VALUE)))
        );

        greenLinePanel.setMaximumSize(new java.awt.Dimension(665, 137));
        greenLinePanel.setMinimumSize(new java.awt.Dimension(665, 137));
        greenLinePanel.setOpaque(false);

        greenLineRouteImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wonderfresh/trainmodel/routeImage/ECE1186greenLine.png"))); // NOI18N

        greenLineLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        greenLineLabel.setForeground(new java.awt.Color(0, 255, 0));
        greenLineLabel.setText("Green");

        javax.swing.GroupLayout greenLinePanelLayout = new javax.swing.GroupLayout(greenLinePanel);
        greenLinePanel.setLayout(greenLinePanelLayout);
        greenLinePanelLayout.setHorizontalGroup(
            greenLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenLinePanelLayout.createSequentialGroup()
                .addComponent(greenLineRouteImage)
                .addGap(0, 152, Short.MAX_VALUE))
            .addGroup(greenLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(greenLinePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(greenLineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(581, Short.MAX_VALUE)))
        );
        greenLinePanelLayout.setVerticalGroup(
            greenLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenLinePanelLayout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(greenLineRouteImage))
            .addGroup(greenLinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(greenLinePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(greenLineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        redLineLightPanel.setOpaque(false);

        yellowSwissvale.setBackground(new java.awt.Color(255, 255, 0));
        yellowSwissvale.setForeground(new java.awt.Color(255, 255, 0));
        yellowSwissvale.setOpaque(true);

        yellowFirst.setBackground(new java.awt.Color(255, 255, 0));
        yellowFirst.setForeground(new java.awt.Color(255, 255, 0));
        yellowFirst.setOpaque(true);

        yellowSouthHills.setBackground(new java.awt.Color(255, 255, 0));
        yellowSouthHills.setForeground(new java.awt.Color(255, 255, 0));
        yellowSouthHills.setOpaque(true);

        yellowHerron.setBackground(new java.awt.Color(255, 255, 0));
        yellowHerron.setForeground(new java.awt.Color(255, 255, 0));
        yellowHerron.setOpaque(true);

        yellowPennStation.setBackground(new java.awt.Color(255, 255, 0));
        yellowPennStation.setForeground(new java.awt.Color(255, 255, 0));
        yellowPennStation.setOpaque(true);

        yellowSteelPlaza.setBackground(new java.awt.Color(255, 255, 0));
        yellowSteelPlaza.setForeground(new java.awt.Color(255, 255, 0));
        yellowSteelPlaza.setOpaque(true);

        yellowStationSquare.setBackground(new java.awt.Color(255, 255, 0));
        yellowStationSquare.setForeground(new java.awt.Color(255, 255, 0));
        yellowStationSquare.setOpaque(true);

        yellowShadyside.setBackground(new java.awt.Color(255, 255, 0));
        yellowShadyside.setForeground(new java.awt.Color(255, 255, 0));
        yellowShadyside.setOpaque(true);

        javax.swing.GroupLayout redLineLightPanelLayout = new javax.swing.GroupLayout(redLineLightPanel);
        redLineLightPanel.setLayout(redLineLightPanelLayout);
        redLineLightPanelLayout.setHorizontalGroup(
            redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redLineLightPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(yellowSwissvale, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(yellowFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(yellowSouthHills, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(yellowHerron, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(398, Short.MAX_VALUE)))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(yellowPennStation, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(281, Short.MAX_VALUE)))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(270, 270, 270)
                    .addComponent(yellowSteelPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(222, Short.MAX_VALUE)))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(386, 386, 386)
                    .addComponent(yellowStationSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(106, Short.MAX_VALUE)))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(yellowShadyside, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(456, Short.MAX_VALUE)))
        );
        redLineLightPanelLayout.setVerticalGroup(
            redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redLineLightPanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yellowFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowSouthHills, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowSwissvale, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(yellowHerron, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(yellowPennStation, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(yellowSteelPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(yellowStationSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
            .addGroup(redLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redLineLightPanelLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(yellowShadyside, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        greenLineLightPanel.setOpaque(false);
        greenLineLightPanel.setPreferredSize(new java.awt.Dimension(500, 111));

        yellowEdgebrook.setBackground(new java.awt.Color(255, 255, 0));
        yellowEdgebrook.setForeground(new java.awt.Color(255, 255, 0));
        yellowEdgebrook.setOpaque(true);

        yellowDormont.setBackground(new java.awt.Color(255, 255, 0));
        yellowDormont.setForeground(new java.awt.Color(255, 255, 0));
        yellowDormont.setText("jLabel7");
        yellowDormont.setOpaque(true);

        yellowMtLebanon.setBackground(new java.awt.Color(255, 255, 0));
        yellowMtLebanon.setForeground(new java.awt.Color(255, 255, 0));
        yellowMtLebanon.setOpaque(true);

        yellowPioneer.setBackground(new java.awt.Color(255, 255, 0));
        yellowPioneer.setForeground(new java.awt.Color(255, 255, 0));
        yellowPioneer.setOpaque(true);

        yellowWhited.setBackground(new java.awt.Color(255, 255, 0));
        yellowWhited.setForeground(new java.awt.Color(255, 255, 0));
        yellowWhited.setOpaque(true);

        yellowCastleShannon.setBackground(new java.awt.Color(255, 255, 0));
        yellowCastleShannon.setForeground(new java.awt.Color(255, 255, 0));
        yellowCastleShannon.setMaximumSize(new java.awt.Dimension(1038, 1000));
        yellowCastleShannon.setMinimumSize(new java.awt.Dimension(1038, 1000));
        yellowCastleShannon.setOpaque(true);

        yellowPoplar.setBackground(new java.awt.Color(255, 255, 0));
        yellowPoplar.setForeground(new java.awt.Color(255, 255, 0));
        yellowPoplar.setOpaque(true);

        yellowGlenbury.setBackground(new java.awt.Color(255, 255, 0));
        yellowGlenbury.setForeground(new java.awt.Color(255, 255, 0));
        yellowGlenbury.setOpaque(true);

        yellowInglewood.setBackground(new java.awt.Color(255, 255, 0));
        yellowInglewood.setForeground(new java.awt.Color(255, 255, 0));
        yellowInglewood.setOpaque(true);

        yellowOverbrook.setBackground(new java.awt.Color(255, 255, 0));
        yellowOverbrook.setForeground(new java.awt.Color(255, 255, 0));
        yellowOverbrook.setOpaque(true);

        yellowStation.setBackground(new java.awt.Color(255, 255, 0));
        yellowStation.setForeground(new java.awt.Color(255, 255, 0));
        yellowStation.setOpaque(true);

        yellowCentral.setBackground(new java.awt.Color(255, 255, 0));
        yellowCentral.setForeground(new java.awt.Color(255, 255, 0));
        yellowCentral.setOpaque(true);

        javax.swing.GroupLayout greenLineLightPanelLayout = new javax.swing.GroupLayout(greenLineLightPanel);
        greenLineLightPanel.setLayout(greenLineLightPanelLayout);
        greenLineLightPanelLayout.setHorizontalGroup(
            greenLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenLineLightPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(greenLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(greenLineLightPanelLayout.createSequentialGroup()
                        .addComponent(yellowEdgebrook, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(359, 359, 359)
                        .addComponent(yellowCastleShannon, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(greenLineLightPanelLayout.createSequentialGroup()
                        .addComponent(yellowPioneer, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(yellowStation, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(yellowWhited, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(yellowCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(yellowInglewood, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(yellowOverbrook, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(yellowGlenbury, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(yellowDormont, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(yellowMtLebanon, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(yellowPoplar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        greenLineLightPanelLayout.setVerticalGroup(
            greenLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenLineLightPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(greenLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yellowWhited, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowStation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowPioneer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowInglewood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowOverbrook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowGlenbury, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowDormont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowMtLebanon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowPoplar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(greenLineLightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yellowCastleShannon, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowEdgebrook, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout routePanelLayout = new javax.swing.GroupLayout(routePanel);
        routePanel.setLayout(routePanelLayout);
        routePanelLayout.setHorizontalGroup(
            routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(routePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, routePanelLayout.createSequentialGroup()
                                .addComponent(numPassengersLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(routePanelLayout.createSequentialGroup()
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(routePanelLayout.createSequentialGroup()
                                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(routePanelLayout.createSequentialGroup()
                                                .addComponent(numCrewLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(routePanelLayout.createSequentialGroup()
                                                .addComponent(tempLabel)
                                                .addGap(42, 42, 42)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27)
                                        .addComponent(numPassengersDisemLabel))
                                    .addComponent(maxPassengerCapacityLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(routePanelLayout.createSequentialGroup()
                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(routePanelLayout.createSequentialGroup()
                                .addComponent(redLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(greenLineLightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(routePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(greenLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(routePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(redLineLightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        routePanelLayout.setVerticalGroup(
            routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, routePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(routePanelLayout.createSequentialGroup()
                        .addComponent(redLinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, routePanelLayout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addComponent(greenLineLightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tempLabel)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numPassengersDisemLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numCrewLabel))
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(maxPassengerCapacityLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numPassengersLabel)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(routePanelLayout.createSequentialGroup()
                    .addComponent(greenLinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 149, Short.MAX_VALUE)))
            .addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(routePanelLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(redLineLightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(107, Short.MAX_VALUE)))
        );
        routePanel.setLayer(numPassengersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(numCrewLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(numPassengersDisemLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(maxPassengerCapacityLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(tempLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(jScrollPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(jScrollPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(redLinePanel, javax.swing.JLayeredPane.PALETTE_LAYER);
        routePanel.setLayer(greenLinePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        routePanel.setLayer(redLineLightPanel, javax.swing.JLayeredPane.MODAL_LAYER);
        routePanel.setLayer(greenLineLightPanel, javax.swing.JLayeredPane.POPUP_LAYER);

        failACButton.setText("Fail A/C");
        failACButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setACFailure(evt);
            }
        });

        failHeatButton.setText("Fail Heat");
        failHeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setHeatFailure(evt);
            }
        });

        failLightsButton.setText("Fail Lights");
        failLightsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLightsFailure(evt);
            }
        });

        failLDoorsButton.setText("Fail Left Doors");
        failLDoorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLeftDoorsFailure(evt);
            }
        });

        failRDoorsButton.setText("Fail Right Doors");
        failRDoorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRightDoorsFailure(evt);
            }
        });

        failBrakesButton.setText("Fail Brakes");
        failBrakesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setServiceBrakesFailure(evt);
            }
        });

        javax.swing.GroupLayout failurePanelLayout = new javax.swing.GroupLayout(failurePanel);
        failurePanel.setLayout(failurePanelLayout);
        failurePanelLayout.setHorizontalGroup(
            failurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(failACButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(failHeatButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(failLightsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(failLDoorsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(failBrakesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(failRDoorsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        failurePanelLayout.setVerticalGroup(
            failurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(failurePanelLayout.createSequentialGroup()
                .addComponent(failACButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(failHeatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(failLightsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(failLDoorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(failRDoorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(failBrakesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(trainIDPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attributePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(routePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(speedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emergencyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(notificationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(failurePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(failurePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trainIDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attributePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(speedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emergencyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(routePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notificationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setRightDoorsFailure(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRightDoorsFailure
        // TODO add your handling code here:
        trainModel.failRightDoors();
    }//GEN-LAST:event_setRightDoorsFailure

    private void setServiceBrakesFailure(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setServiceBrakesFailure
        // TODO add your handling code here:
        trainModel.setServiceBrake(-1, false);
    }//GEN-LAST:event_setServiceBrakesFailure

    private void setEBrakeLabel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setEBrakeLabel
        // TODO add your handling code here:
        eBrakeOnLabel.setForeground(Color.green);
        eBrakeOffLabel.setForeground(new java.awt.Color(120, 120, 120));
        trainModel.activateEBrake();
    }//GEN-LAST:event_setEBrakeLabel

    private void setACFailure(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setACFailure
        // TODO add your handling code here:
        trainModel.setAC(-1);
    }//GEN-LAST:event_setACFailure

    private void setHeatFailure(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setHeatFailure
        // TODO add your handling code here:
        trainModel.setHeat(-1);
    }//GEN-LAST:event_setHeatFailure

    private void setLeftDoorsFailure(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLeftDoorsFailure
        // TODO add your handling code here:
        trainModel.failLeftDoors();
    }//GEN-LAST:event_setLeftDoorsFailure

    private void setLightsFailure(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLightsFailure
        // TODO add your handling code here:
        trainModel.failLights();
    }//GEN-LAST:event_setLightsFailure
    
    public void setUnderground(boolean isUnderground){
        if(isUnderground)
            undergroundLabel.setForeground(Color.green);
        else
            undergroundLabel.setForeground(new java.awt.Color(120, 120, 120));
    }
    public void setTemp(String temp){
        tempBox.setText(temp);
    }
    public void setSpeedLimit(String limit){
        speedLimitBox.setText(limit);
    }
    public void setSpeed(String speedString){
        speedBox.setText(speedString);
    }
    public void setSPS(String speedString){
        spsBox.setText(speedString);
    }
    public void setPowerCmd(String powerCmd){
        powerCmdBox.setText(powerCmd);
    }
    public void setInitials(String capacity, String numCrew, String numPass, String sps, String trainID){
        maxPassCapacityBox.setText(capacity);
        numCrewBox.setText(numCrew);
        numPassBox.setText(numPass);
        spsBox.setText(sps);
        trainIDbox.setText(trainID);
    }
    public void setNotification(String note){
        notificationsBox.append("\n" + note);
    }
    public void setEBrake(boolean status){
        if(status){
            eBrakeOnLabel.setForeground(Color.green);
            eBrakeOffLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else{
            eBrakeOnLabel.setForeground(new java.awt.Color(120, 120, 120));
            eBrakeOffLabel.setForeground(Color.black);
        }
    }
    public void setLine(boolean line){
        //if line == true, green line; else, red line
        if(line){
            //routePanel.setLayer(greenLinePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
            //routePanel.setLayer(redLinePanel, javax.swing.JLayeredPane.PALETTE_LAYER);
            redLinePanel.setVisible(false);
            redLineLabel.setVisible(false);
        }
        else{
            greenLinePanel.setVisible(false);
            greenLineLabel.setVisible(false);
        }
    }
    public void setStation(boolean line, String station, boolean atStation){
        //if line, green line; else, red line
        if(line){
            if(station != null){
                if(station.equals("Pioneer")){
                    //approachingStation.isAtStation(yellowPioneer);
                    yellowPioneer.setVisible(atStation);
                }
                else if(station.equals("Edgebrook")){
                    yellowEdgebrook.setVisible(atStation);
                }
                else if(station.equals("Station")){
                    yellowStation.setVisible(atStation);
                }
                else if(station.equals("Whited")){
                    yellowWhited.setVisible(atStation);
                }
                else if(station.equals("South Bank")){
                    yellowSouthBank.setVisible(atStation);
                }
                else if(station.equals("Central")){
                    yellowCentral.setVisible(atStation);
                }
                else if(station.equals("Inglewood")){
                    yellowInglewood.setVisible(atStation);
                }
                else if(station.equals("Overbrook")){
                    yellowOverbrook.setVisible(atStation);
                }
                else if(station.equals("Glenbury")){
                    yellowGlenbury.setVisible(atStation);
                }
                else if(station.equals("Dormont")){
                    yellowDormont.setVisible(atStation);
                }
                else if(station.equals("Mount Lebanon")){
                    yellowMtLebanon.setVisible(atStation);
                }
                else if(station.equals("Poplar")){
                    yellowPoplar.setVisible(atStation);
                }
                else if(station.equals("Castle Shannon")){
                    yellowCastleShannon.setVisible(atStation);
                }
            }
            //else{
                /*if(station == 2)
                    approachingStation.blink(yellowPioneer);
                else if(station == 9)
                    approachingStation.blink(yellowEdgebrook);
                else if(station == 16)
                    approachingStation.blink(yellowStation);
                else if(station == 22)
                    approachingStation.blink(yellowWhited);
                else if(station == 31)
                    approachingStation.blink(yellowSouthBank);
                else if(station == 39 || station == 141)
                    approachingStation.blink(yellowCentral);
                else if(station == 48 || station == 132)
                    approachingStation.blink(yellowInglewood);
                else if(station == 57 || station == 123)
                    approachingStation.blink(yellowOverbrook);
                else if(station == 65 || station == 114)
                    approachingStation.blink(yellowGlenbury);
                else if(station == 73 || station == 105)
                    approachingStation.blink(yellowDormont);
                else if(station == 77)
                    approachingStation.blink(yellowMtLebanon);
                else if(station == 88)
                    approachingStation.blink(yellowPoplar);
                else if(station == 96)
                    approachingStation.blink(yellowCastleShannon);*/
            //}
        }
        else{
            //if(atStation){
                if(station.equals("Shadyside"))
                    yellowShadyside.setVisible(atStation);
                else if(station.equals("Herron"))
                    yellowHerron.setVisible(atStation);
                else if(station.equals("Swissvale"))
                    yellowSwissvale.setVisible(atStation);
                else if(station.equals("Penn Station"))
                    yellowPennStation.setVisible(atStation);
                else if(station.equals("Steel Plaza"))
                    yellowSteelPlaza.setVisible(atStation);
                else if(station.equals("First Avenue"))
                    yellowFirst.setVisible(atStation);
                else if(station.equals("Station Square"))
                    yellowStationSquare.setVisible(atStation);
                else if(station.equals("South Hills"))
                    yellowSouthHills.setVisible(atStation);
            //}
            //else{
                /*if(station == 7)
                    approachingStation.blink(yellowShadyside);
                else if(station == 16)
                    approachingStation.blink(yellowHerron);
                else if(station == 21)
                    approachingStation.blink(yellowSwissvale);
                else if(station == 25)
                    approachingStation.blink(yellowPennStation);
                else if(station == 35)
                    approachingStation.blink(yellowSteelPlaza);
                else if(station == 45)
                    approachingStation.blink(yellowFirst);
                else if(station == 48)
                    approachingStation.blink(yellowStationSquare);
                else if(station == 60)
                    approachingStation.blink(yellowSouthHills);*/
            //}
        }
    }
    public void blink(javax.swing.JLabel label, boolean visible){
        label.setVisible(visible);
    }
    public void on(int attribute){
        //1 = ac, 2 = heat, 3 = lights, 4 = left doors, 5 = right doors, 6 = service brakes
        if(attribute == 1){
            acOnLabel.setForeground(Color.black);
            acOffLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else if(attribute == 2){
            heatOnLabel.setForeground(Color.black);
            heatOffLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else if(attribute == 3){
            lightsOnLabel.setForeground(Color.black);
            lightsOffLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else if(attribute == 4){
            leftDoorsOpenLabel.setForeground(Color.black);
            doorsClosedLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else if(attribute == 5){
            rightDoorsOpenLabel.setForeground(Color.black);
            doorsClosedLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else{
            serviceBrakesOnLabel.setForeground(Color.black);
            serviceBrakesOffLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
    }
    public void off(int attribute){
        //1 = ac, 2 = heat, 3 = lights, 4 = left doors, 5 = right doors, 6 = service brakes
        if(attribute == 1){
            acOffLabel.setForeground(Color.black);
            acOnLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else if(attribute == 2){
            heatOffLabel.setForeground(Color.black);
            heatOnLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else if(attribute == 3){
            lightsOffLabel.setForeground(Color.black);
            lightsOnLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else if(attribute == 4){
            if(rightDoorsOpenLabel.getForeground() != Color.black)
                doorsClosedLabel.setForeground(Color.black);
            leftDoorsOpenLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else if(attribute == 5){
            if(leftDoorsOpenLabel.getForeground() != Color.black)
                doorsClosedLabel.setForeground(Color.black);
            rightDoorsOpenLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
        else{
            serviceBrakesOffLabel.setForeground(Color.black);
            serviceBrakesOnLabel.setForeground(new java.awt.Color(120, 120, 120));
        }
    }
    public void fail(int attribute){
        //1 = ac, 2 = heat, 3 = lights, 4 = left doors, 5 = right doors, 6 = service brakes
        if(attribute == 1){
            acLabel.setForeground(new java.awt.Color(120, 120, 120));
            acOffLabel.setForeground(new java.awt.Color(120, 120, 120));
            acOnLabel.setForeground(new java.awt.Color(120, 120, 120));
            powerFailureLabel.setForeground(Color.red);
        }
        else if(attribute == 2){
            heatLabel.setForeground(new java.awt.Color(120, 120, 120));
            heatOffLabel.setForeground(new java.awt.Color(120, 120, 120));
            heatOnLabel.setForeground(new java.awt.Color(120, 120, 120));
            powerFailureLabel.setForeground(Color.red);
        }
        else if(attribute == 3){
            lightsLabel.setForeground(new java.awt.Color(120, 120, 120));
            lightsOffLabel.setForeground(new java.awt.Color(120, 120, 120));
            lightsOnLabel.setForeground(new java.awt.Color(120, 120, 120));
            powerFailureLabel.setForeground(Color.red);
        }
        else if(attribute == 4){
            doorsLabel.setForeground(new java.awt.Color(120, 120, 120));
            leftDoorsOpenLabel.setForeground(new java.awt.Color(120, 120, 120));
            powerFailureLabel.setForeground(Color.red);
        }
        else if(attribute == 5){
            doorsLabel.setForeground(new java.awt.Color(120, 120, 120));
            rightDoorsOpenLabel.setForeground(new java.awt.Color(120, 120, 120));
            powerFailureLabel.setForeground(Color.red);
        }
        else{
            serviceBrakeLabel.setForeground(new java.awt.Color(120, 120, 120));
            serviceBrakesOffLabel.setForeground(new java.awt.Color(120, 120, 120));
            serviceBrakesOnLabel.setForeground(new java.awt.Color(120, 120, 120));
            brakeFailureLabel.setForeground(Color.red);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainModelUI(trainModel).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acLabel;
    private javax.swing.JLabel acOffLabel;
    private javax.swing.JLabel acOnLabel;
    private javax.swing.JLabel actualSpeedLabel;
    private javax.swing.JLabel antennaFailureLabel;
    private javax.swing.JPanel attributePanel;
    private javax.swing.JLabel brakeFailureLabel;
    private javax.swing.JLabel doorsClosedLabel;
    private javax.swing.JLabel doorsLabel;
    private javax.swing.JButton eBrakeButton;
    private javax.swing.JLabel eBrakeLabel;
    private javax.swing.JLabel eBrakeOffLabel;
    private javax.swing.JLabel eBrakeOnLabel;
    private javax.swing.JPanel emergencyPanel;
    private javax.swing.JButton failACButton;
    private javax.swing.JButton failBrakesButton;
    private javax.swing.JButton failHeatButton;
    private javax.swing.JButton failLDoorsButton;
    private javax.swing.JButton failLightsButton;
    private javax.swing.JButton failRDoorsButton;
    private javax.swing.JPanel failurePanel;
    private javax.swing.JLabel greenLineLabel;
    private javax.swing.JPanel greenLineLightPanel;
    private javax.swing.JPanel greenLinePanel;
    private javax.swing.JLabel greenLineRouteImage;
    private javax.swing.JLabel heatLabel;
    private javax.swing.JLabel heatOffLabel;
    private javax.swing.JLabel heatOnLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel leftDoorsOpenLabel;
    private javax.swing.JLabel lightsLabel;
    private javax.swing.JLabel lightsOffLabel;
    private javax.swing.JLabel lightsOnLabel;
    private javax.swing.JTextArea maxPassCapacityBox;
    private javax.swing.JLabel maxPassengerCapacityLabel;
    private javax.swing.JPanel notificationPanel;
    private javax.swing.JTextArea notificationsBox;
    private javax.swing.JScrollPane notificationsScrollPane;
    private javax.swing.JTextArea numCrewBox;
    private javax.swing.JLabel numCrewLabel;
    private javax.swing.JTextArea numDisembarkingBox;
    private javax.swing.JTextArea numPassBox;
    private javax.swing.JLabel numPassengersDisemLabel;
    private javax.swing.JLabel numPassengersLabel;
    private javax.swing.JTextArea powerCmdBox;
    private javax.swing.JLabel powerCmdLabel;
    private javax.swing.JLabel powerFailureLabel;
    private javax.swing.JLabel redLineLabel;
    private javax.swing.JPanel redLineLightPanel;
    private javax.swing.JPanel redLinePanel;
    private javax.swing.JLabel redLineRouteImage;
    private javax.swing.JLabel rightDoorsOpenLabel;
    private javax.swing.JLayeredPane routePanel;
    private javax.swing.JLabel serviceBrakeLabel;
    private javax.swing.JLabel serviceBrakesOffLabel;
    private javax.swing.JLabel serviceBrakesOnLabel;
    private javax.swing.JTextArea speedBox;
    private javax.swing.JTextArea speedLimitBox;
    private javax.swing.JLabel speedLimitLabel;
    private javax.swing.JPanel speedPanel;
    private javax.swing.JTextArea spsBox;
    private javax.swing.JLabel spsLabel;
    private javax.swing.JTextArea tempBox;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel trainIDLabel;
    private javax.swing.JPanel trainIDPanel;
    private javax.swing.JTextArea trainIDbox;
    private javax.swing.JLabel undergroundLabel;
    private javax.swing.JLabel yellowCastleShannon;
    private javax.swing.JLabel yellowCentral;
    private javax.swing.JLabel yellowDormont;
    private javax.swing.JLabel yellowEdgebrook;
    private javax.swing.JLabel yellowFirst;
    private javax.swing.JLabel yellowGlenbury;
    private javax.swing.JLabel yellowHerron;
    private javax.swing.JLabel yellowInglewood;
    private javax.swing.JLabel yellowMtLebanon;
    private javax.swing.JLabel yellowOverbrook;
    private javax.swing.JLabel yellowPennStation;
    private javax.swing.JLabel yellowPioneer;
    private javax.swing.JLabel yellowPoplar;
    private javax.swing.JLabel yellowShadyside;
    private javax.swing.JLabel yellowSouthBank;
    private javax.swing.JLabel yellowSouthHills;
    private javax.swing.JLabel yellowStation;
    private javax.swing.JLabel yellowStationSquare;
    private javax.swing.JLabel yellowSteelPlaza;
    private javax.swing.JLabel yellowSwissvale;
    private javax.swing.JLabel yellowWhited;
    // End of variables declaration//GEN-END:variables
}
