/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wonderfresh.trainmodel;

import java.awt.Color;

/**
 *
 * @author Cami
 */
public class TrainModelTestUI extends javax.swing.JFrame {

    static TrainModelTest trainModelTest;
    /**
     * Creates new form TrainModelTestUI
     * @param test
     */
    public TrainModelTestUI(TrainModelTest test) {
        trainModelTest = test;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eBrakeRadioButtons = new javax.swing.ButtonGroup();
        serviceBrakeRadioButtons = new javax.swing.ButtonGroup();
        leftDoorsRadioButtons = new javax.swing.ButtonGroup();
        rightDoorsRadioButtons = new javax.swing.ButtonGroup();
        acRadioButtons = new javax.swing.ButtonGroup();
        heatRadioButtons = new javax.swing.ButtonGroup();
        lightsRadioButtons = new javax.swing.ButtonGroup();
        trainIDButtons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spsText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        authorityText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        numPassText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        beaconText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        eBrakeLabel = new javax.swing.JLabel();
        serviceBrakeLabel = new javax.swing.JLabel();
        leftDoorsLabel = new javax.swing.JLabel();
        rightDoorsLabel = new javax.swing.JLabel();
        powerCmdLabel = new javax.swing.JLabel();
        intGainLabel = new javax.swing.JLabel();
        propGainLabel = new javax.swing.JLabel();
        acLabel = new javax.swing.JLabel();
        heatLabel = new javax.swing.JLabel();
        lightsLabel = new javax.swing.JLabel();
        eBrakeOn = new javax.swing.JRadioButton();
        eBrakeOff = new javax.swing.JRadioButton();
        serviceBrakeOn = new javax.swing.JRadioButton();
        serviceBrakeOff = new javax.swing.JRadioButton();
        leftDoorsOpen = new javax.swing.JRadioButton();
        leftDoorsClosed = new javax.swing.JRadioButton();
        rightDoorsOpen = new javax.swing.JRadioButton();
        rightDoorsClosed = new javax.swing.JRadioButton();
        acOn = new javax.swing.JRadioButton();
        acOff = new javax.swing.JRadioButton();
        heatOn = new javax.swing.JRadioButton();
        heatOff = new javax.swing.JRadioButton();
        lightsOn = new javax.swing.JRadioButton();
        lightsOff = new javax.swing.JRadioButton();
        powerCmdText = new javax.swing.JTextField();
        temperatureText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        trainG1 = new javax.swing.JRadioButton();
        trainG2 = new javax.swing.JRadioButton();
        trainR1 = new javax.swing.JRadioButton();
        trainR2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Antenna (Comm.)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel1.setText("Set Point Speed: ");

        spsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spsTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Authority: ");

        authorityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorityTextActionPerformed(evt);
            }
        });

        jLabel3.setText("mph");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorityText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spsText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(authorityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Track Model", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel4.setText("Number of Passengers at Upcoming Station: ");

        numPassText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPassTextActionPerformed(evt);
            }
        });

        jLabel5.setText("people");

        jLabel6.setText("Beacon Info: ");

        beaconText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beaconTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beaconText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(beaconText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train Controller", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        eBrakeLabel.setText("Emergency Brake: ");

        serviceBrakeLabel.setText("Service Brake: ");

        leftDoorsLabel.setText("Left Doors: ");

        rightDoorsLabel.setText("Right Doors: ");

        powerCmdLabel.setText("Power Command: ");

        intGainLabel.setText("Target Temp: ");

        propGainLabel.setText("Proportional Gain: ");

        acLabel.setText("AC: ");

        heatLabel.setText("Heat: ");

        lightsLabel.setText("Lights: ");

        eBrakeRadioButtons.add(eBrakeOn);
        eBrakeOn.setLabel("On");
        eBrakeOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBrakeOnActionPerformed(evt);
            }
        });

        eBrakeRadioButtons.add(eBrakeOff);
        eBrakeOff.setSelected(true);
        eBrakeOff.setText("Off");
        eBrakeOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBrakeOffActionPerformed(evt);
            }
        });

        serviceBrakeRadioButtons.add(serviceBrakeOn);
        serviceBrakeOn.setText("On");
        serviceBrakeOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceBrakeOnActionPerformed(evt);
            }
        });

        serviceBrakeRadioButtons.add(serviceBrakeOff);
        serviceBrakeOff.setSelected(true);
        serviceBrakeOff.setText("Off");
        serviceBrakeOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceBrakeOffActionPerformed(evt);
            }
        });

        leftDoorsRadioButtons.add(leftDoorsOpen);
        leftDoorsOpen.setText("On");
        leftDoorsOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorsOpenActionPerformed(evt);
            }
        });

        leftDoorsRadioButtons.add(leftDoorsClosed);
        leftDoorsClosed.setSelected(true);
        leftDoorsClosed.setText("Off");
        leftDoorsClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorsClosedActionPerformed(evt);
            }
        });

        rightDoorsRadioButtons.add(rightDoorsOpen);
        rightDoorsOpen.setText("On");
        rightDoorsOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorsOpenActionPerformed(evt);
            }
        });

        rightDoorsRadioButtons.add(rightDoorsClosed);
        rightDoorsClosed.setSelected(true);
        rightDoorsClosed.setText("Off");
        rightDoorsClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorsClosedActionPerformed(evt);
            }
        });

        acRadioButtons.add(acOn);
        acOn.setText("On");
        acOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acOnActionPerformed(evt);
            }
        });

        acRadioButtons.add(acOff);
        acOff.setSelected(true);
        acOff.setText("Off");
        acOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acOffActionPerformed(evt);
            }
        });

        heatRadioButtons.add(heatOn);
        heatOn.setText("On");
        heatOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heatOnActionPerformed(evt);
            }
        });

        heatRadioButtons.add(heatOff);
        heatOff.setSelected(true);
        heatOff.setText("Off");
        heatOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heatOffActionPerformed(evt);
            }
        });

        lightsRadioButtons.add(lightsOn);
        lightsOn.setText("On");

        lightsRadioButtons.add(lightsOff);
        lightsOff.setSelected(true);
        lightsOff.setText("Off");

        powerCmdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerCmdTextActionPerformed(evt);
            }
        });

        temperatureText.setPreferredSize(new java.awt.Dimension(6, 20));
        temperatureText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(eBrakeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eBrakeOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eBrakeOff))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serviceBrakeLabel)
                            .addComponent(leftDoorsLabel)
                            .addComponent(lightsLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(leftDoorsOpen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(leftDoorsClosed))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(serviceBrakeOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serviceBrakeOff))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rightDoorsOpen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rightDoorsClosed))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(acOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acOff))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(heatOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heatOff))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lightsOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lightsOff))))
                    .addComponent(acLabel)
                    .addComponent(rightDoorsLabel)
                    .addComponent(heatLabel))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(powerCmdLabel)
                    .addComponent(propGainLabel)
                    .addComponent(intGainLabel)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(powerCmdText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(temperatureText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eBrakeLabel)
                    .addComponent(powerCmdLabel)
                    .addComponent(eBrakeOn)
                    .addComponent(eBrakeOff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceBrakeLabel)
                    .addComponent(serviceBrakeOn)
                    .addComponent(serviceBrakeOff)
                    .addComponent(powerCmdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftDoorsLabel)
                    .addComponent(leftDoorsOpen)
                    .addComponent(leftDoorsClosed)
                    .addComponent(intGainLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightDoorsLabel)
                    .addComponent(rightDoorsOpen)
                    .addComponent(rightDoorsClosed)
                    .addComponent(temperatureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acLabel)
                    .addComponent(acOn)
                    .addComponent(acOff)
                    .addComponent(propGainLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heatLabel)
                    .addComponent(heatOn)
                    .addComponent(heatOff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightsLabel)
                    .addComponent(lightsOn)
                    .addComponent(lightsOff))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        trainIDButtons.add(trainG1);
        trainG1.setSelected(true);
        trainG1.setText("G1");
        trainG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainG1ActionPerformed(evt);
            }
        });

        trainIDButtons.add(trainG2);
        trainG2.setText("G2");
        trainG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainG2ActionPerformed(evt);
            }
        });

        trainIDButtons.add(trainR1);
        trainR1.setText("R1");
        trainR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainR1ActionPerformed(evt);
            }
        });

        trainIDButtons.add(trainR2);
        trainR2.setText("R2");
        trainR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trainG2)
                    .addComponent(trainG1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainR1)
                    .addComponent(trainR2))
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainG1)
                    .addComponent(trainR1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainG2)
                    .addComponent(trainR2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spsTextActionPerformed
        // TODO add your handling code here:
        //trainModelTest.setSPS(spsText.getText());
    }//GEN-LAST:event_spsTextActionPerformed

    private void authorityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorityTextActionPerformed
        // TODO add your handling code here:
        //trainModelTest.setAuthority(authorityText.getText());
    }//GEN-LAST:event_authorityTextActionPerformed

    private void numPassTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPassTextActionPerformed
        // TODO add your handling code here:
        //trainModelTest.setNumPassengersWaiting(numPassText.getText());
    }//GEN-LAST:event_numPassTextActionPerformed

    private void beaconTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beaconTextActionPerformed
        // TODO add your handling code here:
        //trainModelTest.setBeaconInfo(beaconText.getText());
    }//GEN-LAST:event_beaconTextActionPerformed

    private void powerCmdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerCmdTextActionPerformed
        // TODO add your handling code here:
        trainModelTest.setPowerCmd(powerCmdText.getText());
    }//GEN-LAST:event_powerCmdTextActionPerformed

    private void trainG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainG1ActionPerformed
        // TODO add your handling code here:
        //trainModelTest.setTrainID(1);
    }//GEN-LAST:event_trainG1ActionPerformed

    private void trainG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainG2ActionPerformed
        // TODO add your handling code here:
        //trainModelTest.setTrainID(2);
    }//GEN-LAST:event_trainG2ActionPerformed

    private void trainR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainR1ActionPerformed
        // TODO add your handling code here:
        //trainModelTest.setTrainID(3);
    }//GEN-LAST:event_trainR1ActionPerformed

    private void trainR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainR2ActionPerformed
        // TODO add your handling code here:
        //trainModelTest.setTrainID(4);
    }//GEN-LAST:event_trainR2ActionPerformed

    private void eBrakeOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBrakeOnActionPerformed
        // TODO add your handling code here:
        trainModelTest.setEBrake(true);
    }//GEN-LAST:event_eBrakeOnActionPerformed

    private void eBrakeOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBrakeOffActionPerformed
        // TODO add your handling code here:
        trainModelTest.setEBrake(false);
    }//GEN-LAST:event_eBrakeOffActionPerformed

    protected void setEBrake(boolean status){
        eBrakeRadioButtons.setSelected(eBrakeOn.getModel(), status);
        eBrakeRadioButtons.setSelected(eBrakeOff.getModel(), !status);
    }
    private void heatOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heatOnActionPerformed
        // TODO add your handling code here:
        trainModelTest.setHeat(1);
    }//GEN-LAST:event_heatOnActionPerformed

    private void heatOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heatOffActionPerformed
        // TODO add your handling code here:
        trainModelTest.setHeat(0);
    }//GEN-LAST:event_heatOffActionPerformed

    private void acOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acOnActionPerformed
        // TODO add your handling code here:
        trainModelTest.setAC(1);
    }//GEN-LAST:event_acOnActionPerformed

    private void acOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acOffActionPerformed
        // TODO add your handling code here:
        trainModelTest.setAC(0);
    }//GEN-LAST:event_acOffActionPerformed

    private void rightDoorsOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorsOpenActionPerformed
        // TODO add your handling code here:
        trainModelTest.setDoorsRight(1);
    }//GEN-LAST:event_rightDoorsOpenActionPerformed

    private void rightDoorsClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDoorsClosedActionPerformed
        // TODO add your handling code here:
        trainModelTest.setDoorsRight(0);
    }//GEN-LAST:event_rightDoorsClosedActionPerformed

    private void leftDoorsOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorsOpenActionPerformed
        // TODO add your handling code here:
        trainModelTest.setDoorsLeft(1);
    }//GEN-LAST:event_leftDoorsOpenActionPerformed

    private void leftDoorsClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorsClosedActionPerformed
        // TODO add your handling code here:
        trainModelTest.setDoorsLeft(0);
    }//GEN-LAST:event_leftDoorsClosedActionPerformed

    private void serviceBrakeOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceBrakeOnActionPerformed
        // TODO add your handling code here:
        trainModelTest.setServiceBrake(1);
    }//GEN-LAST:event_serviceBrakeOnActionPerformed

    private void serviceBrakeOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceBrakeOffActionPerformed
        // TODO add your handling code here:
        trainModelTest.setServiceBrake(0);
    }//GEN-LAST:event_serviceBrakeOffActionPerformed

    private void temperatureTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureTextActionPerformed
        // TODO add your handling code here:
        trainModelTest.setTemperature(temperatureText.getText());
    }//GEN-LAST:event_temperatureTextActionPerformed

    public void on(int attribute){
        //1 = ac, 2 = heat, 3 = lights, 4 = left doors, 5 = right doors, 6 = service brakes
        if(attribute == 1){
            acOn.setSelected(true);
            acOff.setSelected(false);
        }
        else if(attribute == 2){
            heatOn.setSelected(true);
            heatOff.setSelected(false);
        }
        else if(attribute == 3){
            lightsOn.setSelected(true);
            lightsOff.setSelected(false);
        }
        else if(attribute == 4){
            leftDoorsOpen.setSelected(true);
            leftDoorsClosed.setSelected(false);
        }
        else if(attribute == 5){
            rightDoorsOpen.setSelected(true);
            rightDoorsClosed.setSelected(false);
        }
        else{
            serviceBrakeOn.setSelected(true);
            serviceBrakeOff.setSelected(false);
        }
    }
    public void off(int attribute){
        //1 = ac, 2 = heat, 3 = lights, 4 = left doors, 5 = right doors, 6 = service brakes
        if(attribute == 1){
            acOn.setSelected(false);
            acOff.setSelected(true);
        }
        else if(attribute == 2){
            heatOn.setSelected(false);
            heatOff.setSelected(true);
        }
        else if(attribute == 3){
            lightsOn.setSelected(false);
            lightsOff.setSelected(true);
        }
        else if(attribute == 4){
            leftDoorsOpen.setSelected(false);
            leftDoorsClosed.setSelected(true);
        }
        else if(attribute == 5){
            rightDoorsOpen.setSelected(false);
            rightDoorsClosed.setSelected(true);
        }
        else{
            serviceBrakeOn.setSelected(false);
            serviceBrakeOff.setSelected(true);
        }
    }
    public void fail(int attribute){
        //1 = ac, 2 = heat, 3 = lights, 4 = left doors, 5 = right doors, 6 = service brakes
        if(attribute == 1){
            acOn.setSelected(false);
            acOff.setSelected(false);
            acLabel.setForeground(Color.red);
        }
        else if(attribute == 2){
            heatOn.setSelected(false);
            heatOff.setSelected(false);
            heatLabel.setForeground(Color.red);
        }
        else if(attribute == 3){
            lightsOn.setSelected(false);
            lightsOff.setSelected(false);
            lightsLabel.setForeground(Color.red);
        }
        else if(attribute == 4){
            leftDoorsOpen.setSelected(false);
            leftDoorsClosed.setSelected(false);
            leftDoorsLabel.setForeground(Color.red);
        }
        else if(attribute == 5){
            rightDoorsOpen.setSelected(false);
            rightDoorsClosed.setSelected(false);
            rightDoorsLabel.setForeground(Color.red);
        }
        else{
            serviceBrakeOn.setSelected(false);
            serviceBrakeOff.setSelected(false);
            serviceBrakeLabel.setForeground(Color.red);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainModelTestUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainModelTestUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainModelTestUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainModelTestUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainModelTestUI(trainModelTest).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acLabel;
    private javax.swing.JRadioButton acOff;
    private javax.swing.JRadioButton acOn;
    private javax.swing.ButtonGroup acRadioButtons;
    private javax.swing.JTextField authorityText;
    private javax.swing.JTextField beaconText;
    private javax.swing.JLabel eBrakeLabel;
    private javax.swing.JRadioButton eBrakeOff;
    private javax.swing.JRadioButton eBrakeOn;
    private javax.swing.ButtonGroup eBrakeRadioButtons;
    private javax.swing.JLabel heatLabel;
    private javax.swing.JRadioButton heatOff;
    private javax.swing.JRadioButton heatOn;
    private javax.swing.ButtonGroup heatRadioButtons;
    private javax.swing.JLabel intGainLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton leftDoorsClosed;
    private javax.swing.JLabel leftDoorsLabel;
    private javax.swing.JRadioButton leftDoorsOpen;
    private javax.swing.ButtonGroup leftDoorsRadioButtons;
    private javax.swing.JLabel lightsLabel;
    private javax.swing.JRadioButton lightsOff;
    private javax.swing.JRadioButton lightsOn;
    private javax.swing.ButtonGroup lightsRadioButtons;
    private javax.swing.JTextField numPassText;
    private javax.swing.JLabel powerCmdLabel;
    private javax.swing.JTextField powerCmdText;
    private javax.swing.JLabel propGainLabel;
    private javax.swing.JRadioButton rightDoorsClosed;
    private javax.swing.JLabel rightDoorsLabel;
    private javax.swing.JRadioButton rightDoorsOpen;
    private javax.swing.ButtonGroup rightDoorsRadioButtons;
    private javax.swing.JLabel serviceBrakeLabel;
    private javax.swing.JRadioButton serviceBrakeOff;
    private javax.swing.JRadioButton serviceBrakeOn;
    private javax.swing.ButtonGroup serviceBrakeRadioButtons;
    private javax.swing.JTextField spsText;
    private javax.swing.JTextField temperatureText;
    private javax.swing.JRadioButton trainG1;
    private javax.swing.JRadioButton trainG2;
    private javax.swing.ButtonGroup trainIDButtons;
    private javax.swing.JRadioButton trainR1;
    private javax.swing.JRadioButton trainR2;
    // End of variables declaration//GEN-END:variables
}
