/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.wonderfresh.commons;
import java.io.File;
import java.util.ArrayList;
//import java.util.Iterator;
import javax.swing.JFileChooser;
import java.util.concurrent.TimeUnit;
import javax.swing.JFrame;

/**
 *
 * @author kwc12
 */
public class TrackModelUI extends javax.swing.JFrame {
    private static int lastTemp;
    private static int currentTemp;
    private static TrackModel newTrack;
    private TrackSimulator trackSimulator;
    private ArrayList<TrackGraph> tempGraphList;
    /**
     * Creates new form TrackModelUI
     * 
     * 
     * 
    public mboUI( Mbo mbo) {
        this.mbo=mbo;
        initComponents();
        
    }
     * 
     * 
     */
    
//    public TrackModelUI( TrackSimulator ts) {
//        this.trackSimulator=ts;
//        newTrack = TrackSimulator.getTrack();
//        initComponents();
//        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
//        
//    }
    
    
    public TrackModelUI(){
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        trackSimulator = TrackSimulator.getInstance();
        newTrack = trackSimulator.getTrack();
        initComponents();
        lastTemp = TrackSimulator.getTemp();
        currentTemp = lastTemp;
        if(newTrack!=null){
            Line.addItem(newTrack.getRedLine().toString());
            Line.addItem(newTrack.getGreenLine().toString());
        }
        
//        Timer timer = new Timer();
//        TimerTask tasknew;
//        tasknew = new TimerTask() {
//
//            @Override
//            public void run() {
//                String lastTemp = Integer.toString(TrackSimulator.getTemp());
//                Auto_Temp_Text_Field.setText(lastTemp);
//            }
//        };
//        timer.schedule(tasknew,10000,10000);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TrainMap = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AutoTab = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Auto_Temp_Text_Field = new javax.swing.JTextPane();
        Auto_Temp_Label = new javax.swing.JLabel();
        Auto_Heater_Label = new javax.swing.JLabel();
        Auto_Heater_Text_Field = new javax.swing.JTextField();
        NotificationBoardLabel = new javax.swing.JLabel();
        TrainsOnTrackLabel = new javax.swing.JLabel();
        TrainsOntrackField = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        AutoTab_SignalLightsText = new javax.swing.JTextArea();
        FailureModesLabel = new javax.swing.JLabel();
        BrokenRailLabel = new javax.swing.JLabel();
        PowerFailureLabel = new javax.swing.JLabel();
        TrackCircuitFailureLabel = new javax.swing.JLabel();
        ToggleBrokenRail = new javax.swing.JToggleButton();
        TogglePowerFailure = new javax.swing.JToggleButton();
        ToggleTrackCircuitFailure = new javax.swing.JToggleButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        NotificationField = new javax.swing.JTextArea();
        ManualTab = new javax.swing.JPanel();
        Manual_Temp_Label = new javax.swing.JLabel();
        Manual_Temp_Field = new javax.swing.JTextField();
        ChangeTempButton = new javax.swing.JButton();
        ChangeTempField = new javax.swing.JTextField();
        ChangeTempLabel = new javax.swing.JLabel();
        ReconfigureTrackLabel = new javax.swing.JLabel();
        SubmitChangeButton = new javax.swing.JButton();
        ChangeLine = new javax.swing.JTextField();
        ChangeSection = new javax.swing.JTextField();
        ChangeBlockNum = new javax.swing.JTextField();
        ChangeBlockLen = new javax.swing.JTextField();
        ChangeSpeed = new javax.swing.JTextField();
        ChangeInfrastructure = new javax.swing.JTextField();
        ChangeArrow = new javax.swing.JTextField();
        ReconfigureEditor = new javax.swing.JTextField();
        DateOfEdit = new javax.swing.JTextField();
        ChangeSwitch = new javax.swing.JTextField();
        HeaterSwitchLabel = new javax.swing.JLabel();
        HeaterOnRadioButton = new javax.swing.JRadioButton();
        HeaterOffRadioButton = new javax.swing.JRadioButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        ManTab_SignalLightText = new javax.swing.JTextArea();
        DemoTab = new javax.swing.JPanel();
        TrackControllerLabel = new javax.swing.JLabel();
        DemoSetSpeed = new javax.swing.JTextField();
        DemoSetAuthority = new javax.swing.JTextField();
        DemoSetLine = new javax.swing.JTextField();
        DemoSetSection = new javax.swing.JTextField();
        DemoSetOrientation = new javax.swing.JTextField();
        DemoSetLight = new javax.swing.JTextField();
        SubmitInfoToTrainButton = new javax.swing.JButton();
        SubmitInfoToTrackButton = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        DemoTab_SignalLightsText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        ArrayList<TrackGraph> tempGraphList;
        Line = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Temp_Gauge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BrokenRail_CheckBox = new javax.swing.JCheckBox();
        TrackCircuitFail_CheckBox = new javax.swing.JCheckBox();
        PowerFailure_CheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        Section = new javax.swing.JComboBox();
        Block_ComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Update_Status = new javax.swing.JLabel();
        Update_Block_Grade = new javax.swing.JLabel();
        Update_Block_Length = new javax.swing.JLabel();
        Update_Crossing = new javax.swing.JLabel();
        Update_Heater = new javax.swing.JLabel();
        Update_Occupied = new javax.swing.JLabel();
        Update_SwitchBlock = new javax.swing.JLabel();
        Update_Station = new javax.swing.JLabel();
        Update_Speed_Limit = new javax.swing.JLabel();
        Update_Underground = new javax.swing.JLabel();
        Update_Arrow_Direction = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("TrackModelUI");

        TrainMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wonderfresh/trackmodel/Track_Layout.png"))); // NOI18N
        TrainMap.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));
        jScrollPane1.setViewportView(TrainMap);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Auto_Temp_Text_Field.setText(newTrack.getTemp());
        jScrollPane7.setViewportView(Auto_Temp_Text_Field);

        Auto_Temp_Label.setText("Temperature º F ");

        Auto_Heater_Label.setText("Heater");

        Auto_Heater_Text_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Auto_Heater_Text_Field.setText("OFF");
        Auto_Heater_Text_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Auto_Heater_Text_FieldActionPerformed(evt);
            }
        });

        NotificationBoardLabel.setText("Messages");

        TrainsOnTrackLabel.setText("Trains On Track");

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        AutoTab_SignalLightsText.setBackground(new java.awt.Color(255, 255, 153));
        AutoTab_SignalLightsText.setColumns(20);
        AutoTab_SignalLightsText.setRows(5);
        AutoTab_SignalLightsText.setText("*Signal Lights: Normal follows tracks in\n alphabetical order. Reverse follows tracks\n in reverse alphabetical order.");
        jScrollPane8.setViewportView(AutoTab_SignalLightsText);

        FailureModesLabel.setText("Failure Modes");

        BrokenRailLabel.setText("Broken Rail:");

        PowerFailureLabel.setText("Power Failure:");

        TrackCircuitFailureLabel.setText("Track Circuit Failure:");

        ToggleBrokenRail.setText("ON/OFF");

        TogglePowerFailure.setText("ON/OFF");

        ToggleTrackCircuitFailure.setText("ON/OFF");

        NotificationField.setColumns(20);
        NotificationField.setRows(5);
        jScrollPane11.setViewportView(NotificationField);

        javax.swing.GroupLayout AutoTabLayout = new javax.swing.GroupLayout(AutoTab);
        AutoTab.setLayout(AutoTabLayout);
        AutoTabLayout.setHorizontalGroup(
            AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutoTabLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TrainsOnTrackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrainsOntrackField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(NotificationBoardLabel)))
                .addGap(126, 126, 126)
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutoTabLayout.createSequentialGroup()
                        .addComponent(Auto_Heater_Label)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutoTabLayout.createSequentialGroup()
                        .addComponent(Auto_Heater_Text_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGap(10, 10, 10)
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Auto_Temp_Label)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TrackCircuitFailureLabel)
                            .addComponent(BrokenRailLabel)
                            .addComponent(PowerFailureLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ToggleBrokenRail)
                            .addComponent(TogglePowerFailure)
                            .addComponent(ToggleTrackCircuitFailure))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(FailureModesLabel)))
                .addContainerGap(1367, Short.MAX_VALUE))
        );
        AutoTabLayout.setVerticalGroup(
            AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addComponent(FailureModesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AutoTabLayout.createSequentialGroup()
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BrokenRailLabel)
                                    .addComponent(ToggleBrokenRail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TogglePowerFailure)
                                    .addComponent(PowerFailureLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ToggleTrackCircuitFailure)
                                    .addComponent(TrackCircuitFailureLabel)))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AutoTabLayout.createSequentialGroup()
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TrainsOnTrackLabel)
                            .addComponent(NotificationBoardLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrainsOntrackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AutoTabLayout.createSequentialGroup()
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Auto_Temp_Label)
                                    .addComponent(Auto_Heater_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AutoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane7)
                                    .addComponent(Auto_Heater_Text_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Auto", AutoTab);

        Manual_Temp_Label.setText("Temperature º F / º C");

        ChangeTempButton.setText("Change Temp");
        ChangeTempButton.setAlignmentX(0.5F);
        ChangeTempButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ChangeTempField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ChangeTempLabel.setText("Change Temperature (º F)");

        ReconfigureTrackLabel.setText("Reconfigure Track");

        SubmitChangeButton.setText("Submit Change");

        ChangeLine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeLine.setText("Line");

        ChangeSection.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeSection.setText("Section");
        ChangeSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSectionActionPerformed(evt);
            }
        });

        ChangeBlockNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeBlockNum.setText("Block #");

        ChangeBlockLen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeBlockLen.setText("Block Length (m)");

        ChangeSpeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeSpeed.setText("Speed Limit (km/h)");

        ChangeInfrastructure.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeInfrastructure.setText("Infrastructure (optional)");

        ChangeArrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeArrow.setText("Arrow Direction (optional)");
        ChangeArrow.setCursor(new java.awt.Cursor(java.awt.Cursor.NE_RESIZE_CURSOR));

        ReconfigureEditor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ReconfigureEditor.setText("Name (editor)");

        DateOfEdit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DateOfEdit.setText("Date");

        ChangeSwitch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChangeSwitch.setText("Switch Block (optional)");

        HeaterSwitchLabel.setText("Heater");

        HeaterOnRadioButton.setSelected(true);
        HeaterOnRadioButton.setText("ON");
        HeaterOnRadioButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        HeaterOffRadioButton.setText("OFF");

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ManTab_SignalLightText.setBackground(new java.awt.Color(255, 255, 153));
        ManTab_SignalLightText.setColumns(20);
        ManTab_SignalLightText.setRows(5);
        ManTab_SignalLightText.setText("*Signal Lights: Normal follows tracks in\n alphabetical order. Reverse follows tracks\n in reverse alphabetical order. ");
        jScrollPane9.setViewportView(ManTab_SignalLightText);

        javax.swing.GroupLayout ManualTabLayout = new javax.swing.GroupLayout(ManualTab);
        ManualTab.setLayout(ManualTabLayout);
        ManualTabLayout.setHorizontalGroup(
            ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualTabLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addComponent(ChangeLine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChangeSection, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChangeBlockNum, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChangeBlockLen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReconfigureEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DateOfEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addComponent(ReconfigureTrackLabel)
                                .addGap(37, 37, 37)
                                .addComponent(SubmitChangeButton)))
                        .addGap(155, 155, 155))
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addComponent(ChangeSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeInfrastructure, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeArrow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChangeSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(HeaterOnRadioButton)
                        .addComponent(HeaterSwitchLabel))
                    .addComponent(HeaterOffRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addComponent(ChangeTempLabel)
                        .addGap(18, 18, 18)
                        .addComponent(Manual_Temp_Label))
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addComponent(ChangeTempField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(Manual_Temp_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ChangeTempButton))
                        .addGap(291, 291, 291)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1374, Short.MAX_VALUE))
        );
        ManualTabLayout.setVerticalGroup(
            ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addComponent(HeaterSwitchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HeaterOnRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HeaterOffRadioButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManualTabLayout.createSequentialGroup()
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReconfigureTrackLabel)
                            .addComponent(SubmitChangeButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChangeLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeBlockNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeBlockLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReconfigureEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateOfEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChangeSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeInfrastructure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeArrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ManualTabLayout.createSequentialGroup()
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Manual_Temp_Label)
                            .addComponent(ChangeTempLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addGroup(ManualTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Manual_Temp_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChangeTempField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChangeTempButton))
                            .addGroup(ManualTabLayout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manual", ManualTab);

        TrackControllerLabel.setText("Track Controller");

        DemoSetSpeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetSpeed.setText("Speed (km/h)");

        DemoSetAuthority.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetAuthority.setText("Authority (m)");

        DemoSetLine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetLine.setText("Line (Red/Green)");
        DemoSetLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoSetLineActionPerformed(evt);
            }
        });

        DemoSetSection.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetSection.setText("Section (Letter)");

        DemoSetOrientation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetOrientation.setText("Orientation (Normal/Reverse)");

        DemoSetLight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DemoSetLight.setText("Light Color (Red/Green)");
        DemoSetLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoSetLightActionPerformed(evt);
            }
        });

        SubmitInfoToTrainButton.setText("Submit to Train");

        SubmitInfoToTrackButton.setText("Submit to Track");

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        DemoTab_SignalLightsText.setBackground(new java.awt.Color(255, 255, 153));
        DemoTab_SignalLightsText.setColumns(20);
        DemoTab_SignalLightsText.setRows(5);
        DemoTab_SignalLightsText.setText("*Signal Lights: Normal follows track in\n alphabetical order. Reverse follows \n track in reverse alphabetical order.");
        jScrollPane10.setViewportView(DemoTab_SignalLightsText);

        javax.swing.GroupLayout DemoTabLayout = new javax.swing.GroupLayout(DemoTab);
        DemoTab.setLayout(DemoTabLayout);
        DemoTabLayout.setHorizontalGroup(
            DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemoTabLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitInfoToTrainButton)
                    .addComponent(SubmitInfoToTrackButton))
                .addGap(18, 18, 18)
                .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DemoTabLayout.createSequentialGroup()
                        .addComponent(DemoSetSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrackControllerLabel)
                            .addComponent(DemoSetAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DemoTabLayout.createSequentialGroup()
                        .addComponent(DemoSetLine, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DemoSetSection, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DemoSetOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DemoSetLight, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(423, 423, 423)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1401, Short.MAX_VALUE))
        );
        DemoTabLayout.setVerticalGroup(
            DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TrackControllerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DemoTabLayout.createSequentialGroup()
                        .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DemoSetSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitInfoToTrainButton)
                            .addComponent(DemoSetAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DemoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DemoSetLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DemoSetSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DemoSetOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DemoSetLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitInfoToTrackButton)))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Demo", DemoTab);

        jScrollPane2.setViewportView(jTabbedPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane12.setViewportView(jTextArea1);

        jLabel2.setText("Occupied Blocks");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane13.setViewportView(jTextArea2);

        jLabel4.setText("Messages");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("PAAC North Shore Track Extension: Track Model");

        Line.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Line" }));
        Line.setToolTipText("");
        Line.setName("Line"); // NOI18N
        Line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineActionPerformed(evt);
            }
        });

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("New Temp");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Update Temperature");

        Temp_Gauge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Temp_Gauge.setText("47°F");
        Temp_Gauge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Temp_GaugeActionPerformed(evt);
            }
        });

        jLabel14.setText("Temperature");

        jLabel15.setText("Heater:");

        jLabel12.setText("Occupied: ");

        jLabel11.setText("Crossing: ");

        jLabel9.setText("Block Grade:");

        jLabel5.setText("Speed Limit: ");

        jLabel6.setText("Failures:");

        BrokenRail_CheckBox.setText("Broken Rail");

        TrackCircuitFail_CheckBox.setText("Track Circuit Fail");

        PowerFailure_CheckBox.setText("Power Fail");
        PowerFailure_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerFailure_CheckBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Section.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Section" }));
        Section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionActionPerformed(evt);
            }
        });

        Block_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Block" }));
        Block_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Block_ComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Block Length: ");

        jLabel10.setText("SwitchBlock:");

        jLabel7.setText("Station: ");

        jLabel13.setText("Status:");

        jLabel18.setText("UnderGround:");

        jLabel19.setText("Arrow Direction:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Temp_Gauge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel6)
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(BrokenRail_CheckBox)
                                            .addGap(10, 10, 10)
                                            .addComponent(TrackCircuitFail_CheckBox))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Update_Heater)
                                                .addComponent(Update_Crossing)
                                                .addComponent(Update_Block_Length)
                                                .addComponent(Update_Block_Grade)
                                                .addComponent(Update_Status))
                                            .addGap(91, 91, 91)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Block_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(PowerFailure_CheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Update_SwitchBlock)
                                    .addComponent(Update_Occupied)
                                    .addComponent(Update_Station)
                                    .addComponent(Update_Speed_Limit)
                                    .addComponent(Update_Underground)
                                    .addComponent(Update_Arrow_Direction))))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Block_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BrokenRail_CheckBox)
                    .addComponent(TrackCircuitFail_CheckBox)
                    .addComponent(PowerFailure_CheckBox)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(Update_Status)
                    .addComponent(Update_Occupied))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(Update_Block_Grade)
                    .addComponent(Update_SwitchBlock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(Update_Block_Length)
                    .addComponent(Update_Station))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(Update_Crossing)
                    .addComponent(Update_Speed_Limit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(Update_Heater)
                    .addComponent(Update_Underground))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Update_Arrow_Direction))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(Temp_Gauge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Main", jPanel3);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Authority");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("SetPointSpeed");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton3.setText("Send Authority and SetPointSpeed");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Test", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane13)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jTabbedPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setBackground(new java.awt.Color(153, 102, 0));
        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Open);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        jTextArea2.setText(filename);
        String warning = trackSimulator.setNewTrack(filename);
        jTextArea2.setText(warning);
        
        
        
    }//GEN-LAST:event_OpenActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        //frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
        setVisible(false);
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void DemoSetLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoSetLightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DemoSetLightActionPerformed

    private void DemoSetLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoSetLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DemoSetLineActionPerformed

    private void ChangeSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeSectionActionPerformed

    private void Auto_Heater_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Auto_Heater_Text_FieldActionPerformed
        // TODO add your handling code here:
        int outside = Integer.parseInt(Auto_Temp_Text_Field.getText());
        if(lastTemp < 32 && outside < 32){
            Auto_Heater_Text_Field.setText("ON");
        }else if(lastTemp <=32 && outside > 37){
            Auto_Heater_Text_Field.setText("OFF");
        }else if(lastTemp > 32 && outside < 32){
            Auto_Heater_Text_Field.setText("ON");
        }
        lastTemp = outside;
    }//GEN-LAST:event_Auto_Heater_Text_FieldActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void SectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionActionPerformed
        // TODO add your handling code here:
        
        if(Section.getSelectedItem().equals("Section")){
            String[] BlockBoxModel = new String[1];
            BlockBoxModel[0] = "Block";
            Block_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(BlockBoxModel));
        }else{
            if(Line.getSelectedItem().equals("Red")){
                ArrayList<Block> blocks = newTrack.getRedLine().getSection((String)Section.getSelectedItem()).getBlockList();
                int blockArraySize = blocks.size();
                System.out.println("Red size "+blockArraySize);
                String[] BlockBoxModel = new String[blockArraySize+1];
                BlockBoxModel[0] = "Block";
                for(int i=0; i<blockArraySize; i++){
                    System.out.println(i);
                    BlockBoxModel[i+1] = Integer.toString(blocks.get(i).getBlockNum());
                }
                Block_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(BlockBoxModel));
//                Iterator<Block> BlockSifter = blocks.iterator();
//                while(BlockSifter.hasNext()){
//                    Block_ComboBox.addItem(BlockSifter.next().getBlockNum());
//                }
            }else{
                ArrayList<Block> blocks = newTrack.getGreenLine().getSection((String)Section.getSelectedItem()).getBlockList();
                int blockArraySize = blocks.size();
                System.out.println("Green size"+blockArraySize);
                String[] BlockBoxModel = new String[blockArraySize+1];
                BlockBoxModel[0] = "Block";
                for(int i=0; i<blockArraySize; i++){
                    BlockBoxModel[i+1] = Integer.toString(blocks.get(i).getBlockNum());
                }
                Block_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(BlockBoxModel));
            }
            
        }
    }//GEN-LAST:event_SectionActionPerformed

    private void PowerFailure_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerFailure_CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerFailure_CheckBoxActionPerformed

    private void Temp_GaugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Temp_GaugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Temp_GaugeActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void LineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineActionPerformed
        // TODO add your handling code here:
            
        
        
        if(Line.getSelectedItem().equals("Red")){
            ArrayList<Section> sections = newTrack.getRedLine().getSections();
            int section_size = sections.size();
            String[] SectionModel = new String[section_size+1];
            SectionModel[0] = "Section";
            for(int i=0; i<section_size; i++){
                SectionModel[i+1] = sections.get(i).getSectionName();
            }
            Section.setModel(new javax.swing.DefaultComboBoxModel<String>(SectionModel));
        }else if(Line.getSelectedItem().equals("Green")){
            ArrayList<Section> sections = newTrack.getGreenLine().getSections();
            int section_size = sections.size();
            String[] SectionModel = new String[section_size+1];
            SectionModel[0] = "Section";
            for(int i=0; i<section_size; i++){
                SectionModel[i+1] = sections.get(i).getSectionName();
            }
            Section.setModel(new javax.swing.DefaultComboBoxModel<String>(SectionModel));
        }else{
            String[] SectionModel = new String[1];
            SectionModel[0] = "Section";
            Section.setModel(new javax.swing.DefaultComboBoxModel<String>(SectionModel));
        }
        
       
    }//GEN-LAST:event_LineActionPerformed

    private void Block_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Block_ComboBoxActionPerformed
        // TODO add your handling code here:
        Block tempBlock;
        if(!Block_ComboBox.getSelectedItem().equals("Block")){
            if(Line.getSelectedItem().equals("Red")){
                //int numSelect = Integer.parseInt((String)Block_ComboBox.getSelectedItem());
                tempBlock = newTrack.getRedLine().getBlock("Red", Integer.parseInt((String)Block_ComboBox.getSelectedItem()));
            }else{
                //int numSelect = Integer.parseInt((String)Block_ComboBox.getSelectedItem());
                tempBlock = newTrack.getGreenLine().getBlock("Green", Integer.parseInt((String)Block_ComboBox.getSelectedItem()));
            }
            
            //Update_Status.add(this)
            Update_Block_Grade.setText(Double.toString(tempBlock.getBlockGrade())+"%");
            double len = tempBlock.getBlockLength();
            len = len*3.28084;
            String lenText = String.format("%.2f ft", len);
            Update_Block_Length.setText(lenText);
            if(tempBlock.isCrossing()){
                Update_Crossing.setText("True");
            }else{
                Update_Crossing.setText("False");
            }
            if(tempBlock.isUnderground()){
                Update_Underground.setText("True");
            }else{
                Update_Underground.setText("False");
            }
            int current_speedLimit = tempBlock.getSpeedLimit();
            double speedMPH = current_speedLimit*0.621371;
            String speedText = String.format("%.2f mph", speedMPH);
            Update_Speed_Limit.setText(speedText);
            if(tempBlock.isStation()){
                Update_Station.setText(tempBlock.getStation());
            }else{
                Update_Station.setText("None");
            }
            if(tempBlock.isOccupied()){
                Update_Occupied.setText("True");
            }else{
                Update_Occupied.setText("False");
            }
            if(tempBlock.getSwitchBlock()>-1){
                Update_SwitchBlock.setText(Integer.toString(tempBlock.getSwitchBlock()));
            }else{
                Update_SwitchBlock.setText("No Switch");
            }
            if(tempBlock.closed){
                Update_Status.setText("Closed");
            }else{
                Update_Status.setText("Open");
            }
            String arrowString;
            if(tempBlock.getLine().equals("Red")){
                Section tempSection = newTrack.getRedLine().getSection(tempBlock.getSection());
                arrowString = tempSection.getArrowDirection();
            }else{
                Section tempSection = newTrack.getGreenLine().getSection(tempBlock.getSection());
                arrowString = tempSection.getArrowDirection();
            }
            if(arrowString.startsWith("Head")&&arrowString.endsWith("Head")){
                Update_Arrow_Direction.setText("Head <-> Head");
            }else if(arrowString.startsWith("Head")&&arrowString.endsWith("Tail")){
                Update_Arrow_Direction.setText("Head <- Tail");
            }else{
                Update_Arrow_Direction.setText("Tail -> Head");
            }
            if(tempBlock.isStation()&&(lastTemp<=32)){
                Update_Heater.setText("On");
            }else{
                Update_Heater.setText("Off");
            }
            if(tempBlock.hasBrokenTrackFailure() && !BrokenRail_CheckBox.isSelected()){
                BrokenRail_CheckBox.doClick();
            }else if(!tempBlock.hasBrokenTrackFailure() && BrokenRail_CheckBox.isSelected()){
                BrokenRail_CheckBox.doClick();
            }
            if(tempBlock.hasTrackCircuitFailure() && !TrackCircuitFail_CheckBox.isSelected()){
                TrackCircuitFail_CheckBox.doClick();
            }else if(!tempBlock.hasTrackCircuitFailure() && TrackCircuitFail_CheckBox.isSelected()){
                TrackCircuitFail_CheckBox.doClick();
            }
            if(tempBlock.hasPowerFailure() && !PowerFailure_CheckBox.isSelected()){
                PowerFailure_CheckBox.doClick();
            }else if(!tempBlock.hasPowerFailure() && PowerFailure_CheckBox.isSelected()){
                PowerFailure_CheckBox.doClick();
            }
            
        }
    }//GEN-LAST:event_Block_ComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Block temp;
        if(Line.getSelectedItem().equals("Red")){
            temp = newTrack.getRedLine().getBlock("Red", Integer.parseInt((String)Block_ComboBox.getSelectedItem()));
        }else if(Line.getSelectedItem().equals("Green")){
            temp = newTrack.getGreenLine().getBlock("Green", Integer.parseInt((String)Block_ComboBox.getSelectedItem()));
        }else{
            return;
        }
        if(BrokenRail_CheckBox.isSelected()){
            temp.BrokenTrackFailure(true);
        }else{
            temp.BrokenTrackFailure(false);
        }
        if(TrackCircuitFail_CheckBox.isSelected()){
            temp.TrackCircuitFailure(true);
        }else{
            temp.TrackCircuitFailure(false);
        }
        if(PowerFailure_CheckBox.isSelected()){
            temp.PowerFailure(true);
        }else{
            temp.PowerFailure(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            int newTemp = Integer.parseInt(jTextField2.getText());
            if(currentTemp>=33 && lastTemp >= 39){
                lastTemp = currentTemp;
                currentTemp = newTemp;
                Temp_Gauge.setText(Integer.toString(newTemp)+"°F");
            }else if(currentTemp<=32 && lastTemp>=33){
                lastTemp = currentTemp;
                currentTemp = newTemp;
                Temp_Gauge.setText(Integer.toString(newTemp)+"°F");
            }else{
                Temp_Gauge.setText(Integer.toString(newTemp)+"°F");
            }
        }catch(NumberFormatException e){
            jTextField2.setText("N/A");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void runTheTrack() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        System.out.println("TrackModelUI is running.");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackModelUI().setVisible(true);
                new updateOccuppiedBlocks().start();
                new updateTemp().start();

            }
        });
    }
    
    private static class updateTemp extends Thread{
        public void run(){
            Time clock = Time.getInstance();
            int speed = clock.getSpeed();
            while(!Thread.interrupted()){
                try{
                    if(speed == 1){
                        TimeUnit.SECONDS.sleep(1);
                    }else{
                        TimeUnit.SECONDS.sleep(1);
                    }
                }catch(InterruptedException e){
                }
                double newNum = Math.random()*15;
                lastTemp = currentTemp;
                if(newNum<2){
                    currentTemp -= 2;
                }else if(newNum<5){
                    currentTemp -= 1;
                }else if(newNum<10){
                    currentTemp = currentTemp;
                }else if(newNum<13){
                    currentTemp += 1;
                }else{
                    currentTemp += 2;
                }
                Temp_Gauge.setText(Integer.toString(currentTemp)+"°F");
                TrackSimulator.saveTemp(currentTemp);
            }
        }
    }
    
    private static class updateOccuppiedBlocks extends Thread{
        
        public void run(){
                  while(!Thread.interrupted()){
//                    try{
//                        TimeUnit.SECONDS.sleep(1);
//                    }catch(InterruptedException e){
//                        System.out.println("exit trackUI");
//                    }
                    ArrayList<Block> OccupiedBlocksRed = newTrack.getRedLine().getOccupiedBlocks();
                    ArrayList<Block> OccupiedBlocksGreen = newTrack.getGreenLine().getOccupiedBlocks();
                    int RedSizeO = OccupiedBlocksRed.size();
                    int GreenSizeO = OccupiedBlocksGreen.size();
                    String[] OccupiedString = new String[RedSizeO+GreenSizeO];
                    String OccupiedText = "";
                    for(int i=0; i<RedSizeO; i++){
                        OccupiedString[i] = OccupiedBlocksRed.get(i).getLabel();
                    }
                    for(int j=0; j<GreenSizeO; j++){
                        OccupiedString[RedSizeO+j] = OccupiedBlocksGreen.get(j).getLabel();
                    }
                    int rows = 0;
                    for(int k=0; k<OccupiedString.length; k++){
                        if(rows<5){
                            OccupiedText.concat(OccupiedString[k]+"\t");
                        }else{
                            rows = 0;
                            OccupiedText.concat(OccupiedString[k]+"\n");
                        }
                    }
                    jTextArea1.setText(OccupiedText);
                }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AutoTab;
    private javax.swing.JTextArea AutoTab_SignalLightsText;
    private javax.swing.JLabel Auto_Heater_Label;
    private javax.swing.JTextField Auto_Heater_Text_Field;
    private javax.swing.JLabel Auto_Temp_Label;
    private javax.swing.JTextPane Auto_Temp_Text_Field;
    private javax.swing.JComboBox Block_ComboBox;
    private javax.swing.JLabel BrokenRailLabel;
    private javax.swing.JCheckBox BrokenRail_CheckBox;
    private javax.swing.JTextField ChangeArrow;
    private javax.swing.JTextField ChangeBlockLen;
    private javax.swing.JTextField ChangeBlockNum;
    private javax.swing.JTextField ChangeInfrastructure;
    private javax.swing.JTextField ChangeLine;
    private javax.swing.JTextField ChangeSection;
    private javax.swing.JTextField ChangeSpeed;
    private javax.swing.JTextField ChangeSwitch;
    private javax.swing.JButton ChangeTempButton;
    private javax.swing.JTextField ChangeTempField;
    private javax.swing.JLabel ChangeTempLabel;
    private javax.swing.JTextField DateOfEdit;
    private javax.swing.JTextField DemoSetAuthority;
    private javax.swing.JTextField DemoSetLight;
    private javax.swing.JTextField DemoSetLine;
    private javax.swing.JTextField DemoSetOrientation;
    private javax.swing.JTextField DemoSetSection;
    private javax.swing.JTextField DemoSetSpeed;
    private javax.swing.JPanel DemoTab;
    private javax.swing.JTextArea DemoTab_SignalLightsText;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JLabel FailureModesLabel;
    private javax.swing.JRadioButton HeaterOffRadioButton;
    private javax.swing.JRadioButton HeaterOnRadioButton;
    private javax.swing.JLabel HeaterSwitchLabel;
    private javax.swing.JComboBox Line;
    private javax.swing.JTextArea ManTab_SignalLightText;
    private javax.swing.JPanel ManualTab;
    private javax.swing.JTextField Manual_Temp_Field;
    private javax.swing.JLabel Manual_Temp_Label;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel NotificationBoardLabel;
    private javax.swing.JTextArea NotificationField;
    private javax.swing.JMenuItem Open;
    private javax.swing.JLabel PowerFailureLabel;
    private javax.swing.JCheckBox PowerFailure_CheckBox;
    private javax.swing.JTextField ReconfigureEditor;
    private javax.swing.JLabel ReconfigureTrackLabel;
    private javax.swing.JComboBox Section;
    private javax.swing.JButton SubmitChangeButton;
    private javax.swing.JButton SubmitInfoToTrackButton;
    private javax.swing.JButton SubmitInfoToTrainButton;
    private static javax.swing.JTextField Temp_Gauge;
    private javax.swing.JToggleButton ToggleBrokenRail;
    private javax.swing.JToggleButton TogglePowerFailure;
    private javax.swing.JToggleButton ToggleTrackCircuitFailure;
    private javax.swing.JCheckBox TrackCircuitFail_CheckBox;
    private javax.swing.JLabel TrackCircuitFailureLabel;
    private javax.swing.JLabel TrackControllerLabel;
    private javax.swing.JLabel TrainMap;
    private javax.swing.JLabel TrainsOnTrackLabel;
    private javax.swing.JTextField TrainsOntrackField;
    private javax.swing.JLabel Update_Arrow_Direction;
    private javax.swing.JLabel Update_Block_Grade;
    private javax.swing.JLabel Update_Block_Length;
    private javax.swing.JLabel Update_Crossing;
    private javax.swing.JLabel Update_Heater;
    private javax.swing.JLabel Update_Occupied;
    private javax.swing.JLabel Update_Speed_Limit;
    private javax.swing.JLabel Update_Station;
    private javax.swing.JLabel Update_Status;
    private javax.swing.JLabel Update_SwitchBlock;
    private javax.swing.JLabel Update_Underground;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private static javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
